---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Tema 1:  Distribuciones bivariadas (multivariadas)

En el caso univariado se tenia a una va $X$ definida en los reales $IR$, a esta va se le asignaba una función de distribución $F(x)$ y una función de densidad $f(x)$. Ambas distribuciones tienen su correspondencia en lo discreto y lo continuo:

Caso discreto:

$$\sum_{Rx} P(X=x)=1$$
$$F(t)=P(X\leq t)=\sum_{x\leq t} P(X=x)$$

Caso continuo:

$$\int_{Rx}f(x)dx=1$$

$$F(t)=P(X\leq t)=\int_{-\infty}^{t}f(x)dx$$


La idea de este capitulo es ver las propiedades en el caso bivariante y generalizar para el caso multivariante.

## Variables aleatorias bivariantes

Son un par de variables aleatorias con una distribución conjunta, son típicamente representadas con mayúscula $(X, Y)$ o $(X_1,X_2)$, las realizaciones de estas variables aleatorias se representan como $(x,y)$ o $(x_1,x_2)$.

> Definición 1. 
Un par de variables aleatorias bivariadas es un par numérico de resultados; una función definida en $IR^2$

Ejemplos: 

  * Considerar el par (edad, estatura):
    + $(23,170)$
    + $(20,172)$
    + $(20,154)$
    + $(26,159)$
    + $(19,175)$
  * Considerar el par: (ingreso, años experiencia)
  
Imaginar lanzar 2 monedas simultáneamente, $\Omega=\{CC,CS,SC,SS\}$, si definimos a $Cara=1$ y $Sello=0$, $R_{(X,Y)}=\{(1,1),(1,0),(0,1),(0,0)\}$.

## Función de distribución bivariada

> Definición 2.

La función de distribución conjunta de $(X,Y)$ es 

$$F(x,y)=P(X\leq x,Y\leq y)=P\left[\{X\leq x\} \cap \{Y\leq y\}  \right]$$
Las propiedades de $F$ son similares al caso univariante, $0\leq F(x,y)\leq 1$.

Ejemplo: 

$$F(x,y)=(1-e^{-x})(1-e^{-y});\hspace{2cm} x,y\geq0 $$
  * $F(0,0)=0$
  * $F(\infty,\infty)=1$


Calcular: 

  $$P(X\leq 10,Y\leq 100)=F(10,100)=(1-e^{-10})(1-e^{-100})=0.9999546$$
  $$P(X\leq 5,Y\leq 20)=F(5,20)=0.99326$$

 La distribución conjunta satisface:
 
 $$P(a<X\leq b,c< Y\leq d)=F(b,d)-F(b,c)-F(a,d)+F(a,c)$$

Para $a<b$ y $c<d$

## Función masa de probabilidad (función de densidad)

Para el par $(X,Y)$ con una función de distribución conjunta $F(x,y)$.

Para el caso continuo,

> Definición 3. 

$$f(x,y)=\frac{\partial^2}{\partial x \partial y}F(x,y)$$

Por un tema de notación, a veces escribiremos $f_{X,Y}(x,y)$

Ejercicio: encontrar $f(x,y)$ para la $F$ dada en el ejemplo anterior

$$f(x,y)=\frac{\partial^2}{\partial x \partial y}\left[(1-e^{-x})(1-e^{-y})\right]=e^{-x}e^{-y}$$

$f$ satisface de forma similar las propiedades vistas en el caso univariante.

$$\int_{Rx}\int_{Ry}f(x,y)dydx=1$$

Para el ejercicio:

$$\int_0^{\infty} \int_0^{\infty}e^{-x}e^{-y} dx dy=\int_0^{\infty} e^{-y} \left[-e^{-x}/_0^{\infty} \right] dy =1$$

$$P(a<X\leq b,c< Y\leq d)=\int_a^b \int_c^d f(x,y)dxdy$$


* ¿Qué relación existe entre estas dos variables?
* Serán independientes
* ¿Cómo se afectan entre ellas?


