# Tema 2: Distribuciones muestrales

A partir de este tema la estadística esta vinculada con la *inferencia* sobre los *parámetros* de la información/datos.

## Muestras y población

> Definición: Una población es una colección de objetos, estos objetos tienen variables.

Sea nuestra población $U$, esta población puede ser finita o infinita

Finitas,
$$U=\{u_1, u_2, \ldots , u_i,...,u_N \}$$
Infinita,

$$U=\{u_1, u_2, \ldots , u_i,... \}$$


Cada elemento de $U$ tiene variables o características asociadas:

$$u_i=\{X_{i1}, X_{i2}, \ldots, X_{iP} \}$$
$$u_j=\{X_{j1}, X_{j2}, \ldots, X_{jP} \}$$

> Definición, Muestra: Una muestra es un subconjunto de U.

Normalmente una muestra tiene un tamaño $n$, el mecanismo para obtener la muestra de $U$ puede ser con reposición o sin reposición, en cualquier caso podemos anotar esto de la siguiente forma, sea $s$ una muestra:

$$s=\{u_{1}^*,u_2^*, \ldots, u_n^* \}$$
Note que los elementos $u_1$ y $u_1^*$ no necesariamente son los mismos.

El subconjunto $s$ no es único y en realidad existen muchas muestras posibles, según el contexto, esto depende:

  * Del tamaño de $N$, $n$
  * Del mecanismo s/rep, c/rep.

Ejercicios, 

  1. Sea la población $U=\{a,b,c,d,e,f\}$, se define una muestra de $n=3$, escriba todas las muestras posibles según ambos mecanismos de reposición.

Solución,  
  * (s/rep), 20: $s_1=\{a,b,c\}$, $s_2=\{a,b,d \}$, $\ldots$ ,$s_{20}=\{d,e,f\}$ 
  * (c/rep), 216: $s_1=\{a,a,a\}$, $s_2={a,a,b}$, $\ldots$, $s_{216}=\{f,f,f\}$  
  
  2. En una población de 90 estudiantes, si se define una muestra de 10 estudiantes, según ambos mecanismos de selección ¿Cuantas muestras se pueden armar?
  * s/rep: 5720645481903
  * c/rep: 34867844009999998976  

Sin reposición:

$$Muestras_{Posibles}=\binom{N}{n}$$

Con reposición:

$$Muestras_{Posibles}=N^n$$

Imaginemos a la primera variable de interés $X_1$, para el universo esta variable tiene los elementos:

$$X_1=\{X_{11}, X_{21}, X_{31}, \ldots, X_{N1} \}$$

Imaginemos que observamos a $X_1$, para la muestra.

$$X_1^*=\{X_{11}^*, X_{21}^*, X_{31}^*, \ldots, X_{n1}^* \}$$

Estos $X_{i1}^*$ para los $i=1,\ldots,n$ son variables aleatorias. Por lo tanto $X_1$ es un vector aleatorio de tamaño $n$.

De ahora en adelante vamos a trabajar con un solo vector aleatorio denominado $X$, de tal forma que este sea la colección de $n$ variables aleatorias. 

$$X=\{X_1,X_2,\ldots,X_n \}$$

> Definición.

La colección del vector aleatorio $X=\{X_1,X_2,\ldots,X_n \}$, son independientes e idénticamente distribuidas (iid) si la distribución conjunta de las $n$ variables puede ser escrita como $f(x_1,x_2,\ldots,x_n)=f(x_1)*f(x_2)*\ldots*f(x_n)$ y además todas las $x_i$ tienen la misma función de distribución $F(x)$.

> Definición

Sea $N$ el tamaño de la población y $n$ el tamaño de la muestra, ambos valores para fines de este capítulo son fijas o constantes.

## Parámetros, estadísticas y estimadores.

El objetivo de la estadística es aprender acerca de las características de una población. Estas características las vamos a llamar *parámetros*.

> Definición,

Un parámetro $\theta$ es una función sobre la población $U$.

$$\theta=f(U,X,Y,Z,\ldots)$$
Nota: Los parámetros de una población son constantes.

Ejemplo, sea el universo los 10 primeros números naturales y sus valores. $Y=\{1,2,3,4,5,6,7,8,9,10\}$. Sobre estos valores de esta población de $N=10$ se pueden calcular los siguientes parámetros.

  * Total
  
$$\theta_1=t_y=\sum_U y_i=55$$
  * Media
  
$$\theta_2=\mu_y=\frac{t_y}{N}=\frac{55}{10}=5.5$$

  * Máximo: $\theta_3=max(y)=10$
  * Mínimo: $\theta_4=max(y)=1$

Es posibles hacer transformaciones sobre $Y$, sea $Z$ una variables binaria que identifique a los números primos de $Y$; $1=primo$, $0=\sim primo$

$$Z=\{1,1,1,0,1,0,1,0,0,0 \}$$

Calcular el promedio de $Z$

$$\theta_5=\mu_z=\frac{5}{10}=0.5$$

Cuando obtenemos la media de un vector binario, obtenemos lo que se denomina un proporción

$$\theta_5=P_a=\frac{\#A}{N}$$

$$\theta_5=P_{primos}=\frac{\#primos}{N}$$


> Definición, estadística

Se denomina estadística a una función sobre la muestra

> Definición, estimador

Un estimador $\hat{\theta}$ para el parámetro $\theta$ es una **estadística** que busca aproximar/adivinar el valor de $\theta$

Ejemplo, para la variable $Y=\{1,2,3,4,5,6,7,8,9,10\}$, imaginar que se selecciona un muestra de tamaño $n=4$ s/rep.

La cantidad de muestras posibles es de 210, supongamos que realizamos 2 procesos de selección para la muestra y obtenemos:

  * $s_1=\{8, 1, 3, 7\}$
  * $s_2=\{8, 2, 6, 5\}$

Sabemos que el parámetro del total de $Y$ es $t_y=55$, ¿Qué? función se puede aplicar sobre la muestra para postular a un estimador que se aproxime a $t_y$ sobre las 2 muestras seleccionadas

$$\hat{\theta}_1=\hat{t}_y=\sum_s y_i$$

Para $s_1$ el valor del estimador es de $\hat{t}_{y,s1}=19$, $\hat{t}_{y,s2}=21$, los valores evaluados sobre una muestra y un estimador se conoce como estimación

$$\hat{\theta}_2=\hat{t}_y=\prod_s y_i$$

Las estimaciones con el estimador propuesto $\hat{t}_{y,s1}=8*1*3*7=168$, $\hat{t}_{y,s1}=480$

$$\hat{\theta}_3=\frac{\prod_s y_i}{3}$$

$\hat{t}_{y,s1}=56$, $\hat{t}_{y,s2}=160$

$$\hat{\theta}_4=\frac{\sum_{s}y_i^2}{2}$$

$\hat{t}_{y,s1}=61.5$, $\hat{t}_{y,s2}=64.5$

$$\hat{\theta}_5=\frac{N}{n} \sum_{s}y_i $$

$\hat{t}_{y,s1}=47.5$, $\hat{t}_{y,s2}=52.5$
