<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Estimaciones | Estadística II</title>
  <meta name="description" content="Este libro esta destinado a la materia de Estadística II de la carrera de Estadística de la Universidad Mayor de San Andres." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Estimaciones | Estadística II" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este libro esta destinado a la materia de Estadística II de la carrera de Estadística de la Universidad Mayor de San Andres." />
  <meta name="github-repo" content="alvarolimber/EST-145" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Estimaciones | Estadística II" />
  
  <meta name="twitter:description" content="Este libro esta destinado a la materia de Estadística II de la carrera de Estadística de la Universidad Mayor de San Andres." />
  

<meta name="author" content="Alvaro Chirino Gutierrez" />


<meta name="date" content="2022-11-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tema-2-distribuciones-muestrales.html"/>
<link rel="next" href="prueba-de-hipótesis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audiencia"><i class="fa fa-check"></i>Audiencia</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-acuerdos"><i class="fa fa-check"></i>Software y acuerdos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bases-de-datos"><i class="fa fa-check"></i>Bases de datos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimiento"><i class="fa fa-check"></i>Agradecimiento</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html"><i class="fa fa-check"></i><b>1</b> Distribuciones de probabilidad conjunta</a>
<ul>
<li class="chapter" data-level="1.1" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#variables-aleatorias-bivariantes"><i class="fa fa-check"></i><b>1.1</b> Variables aleatorias bivariantes</a></li>
<li class="chapter" data-level="1.2" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#función-de-distribución-bivariada"><i class="fa fa-check"></i><b>1.2</b> Función de distribución bivariada</a></li>
<li class="chapter" data-level="1.3" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#distribución-marginal"><i class="fa fa-check"></i><b>1.3</b> Distribución marginal</a></li>
<li class="chapter" data-level="1.4" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#independencia"><i class="fa fa-check"></i><b>1.4</b> Independencia</a></li>
<li class="chapter" data-level="1.5" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#valores-esperados"><i class="fa fa-check"></i><b>1.5</b> Valores esperados</a></li>
<li class="chapter" data-level="1.6" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#distribuciones-condicionales"><i class="fa fa-check"></i><b>1.6</b> Distribuciones condicionales</a></li>
<li class="chapter" data-level="1.7" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#esperanza-condicional"><i class="fa fa-check"></i><b>1.7</b> Esperanza condicional</a></li>
<li class="chapter" data-level="1.8" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#medidas-de-relación-entre-dos-variables"><i class="fa fa-check"></i><b>1.8</b> Medidas de relación entre dos variables</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#ejemplo"><i class="fa fa-check"></i><b>1.8.1</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#transformaciones"><i class="fa fa-check"></i><b>1.9</b> Transformaciones</a></li>
<li class="chapter" data-level="1.10" data-path="distribuciones-de-probabilidad-conjunta.html"><a href="distribuciones-de-probabilidad-conjunta.html#distrubuciones-conjuntas-de-más-de-2-variables-aleatorias"><i class="fa fa-check"></i><b>1.10</b> Distrubuciones conjuntas de más de 2 variables aleatorias</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html"><i class="fa fa-check"></i><b>2</b> Tema 2: Distribuciones muestrales</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#muestras-y-población"><i class="fa fa-check"></i><b>2.1</b> Muestras y población</a></li>
<li class="chapter" data-level="2.2" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#parámetros-estadísticas-y-estimadores."><i class="fa fa-check"></i><b>2.2</b> Parámetros, estadísticas y estimadores.</a></li>
<li class="chapter" data-level="2.3" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-muestral"><i class="fa fa-check"></i><b>2.3</b> Distribución muestral</a></li>
<li class="chapter" data-level="2.4" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#propiedades-de-los-estimadores"><i class="fa fa-check"></i><b>2.4</b> Propiedades de los estimadores</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#estimador-insesgado"><i class="fa fa-check"></i><b>2.4.1</b> Estimador insesgado</a></li>
<li class="chapter" data-level="2.4.2" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#estimador-eficiente"><i class="fa fa-check"></i><b>2.4.2</b> Estimador eficiente</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-muestral-para-la-media"><i class="fa fa-check"></i><b>2.5</b> Distribución muestral para la media</a></li>
<li class="chapter" data-level="2.6" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#teorema-del-límite-central"><i class="fa fa-check"></i><b>2.6</b> Teorema del límite central</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#simulación-del-teorema-del-límite-central"><i class="fa fa-check"></i><b>2.6.1</b> Simulación del teorema del límite central</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-muestral-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>2.7</b> Distribución muestral para la diferencia de medias</a></li>
<li class="chapter" data-level="2.8" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-muestral-para-la-proporción"><i class="fa fa-check"></i><b>2.8</b> Distribución muestral para la proporción</a></li>
<li class="chapter" data-level="2.9" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-muestral-para-la-varianza"><i class="fa fa-check"></i><b>2.9</b> Distribución muestral para la varianza</a></li>
<li class="chapter" data-level="2.10" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-chi2"><i class="fa fa-check"></i><b>2.10</b> Distribución <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="2.11" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-t-student"><i class="fa fa-check"></i><b>2.11</b> Distribución t-student</a></li>
<li class="chapter" data-level="2.12" data-path="tema-2-distribuciones-muestrales.html"><a href="tema-2-distribuciones-muestrales.html#distribución-fisher-f"><i class="fa fa-check"></i><b>2.12</b> Distribución Fisher (F)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estimaciones.html"><a href="estimaciones.html"><i class="fa fa-check"></i><b>3</b> Estimaciones</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estimaciones.html"><a href="estimaciones.html#inferencia-estadística"><i class="fa fa-check"></i><b>3.1</b> Inferencia estadística</a></li>
<li class="chapter" data-level="3.2" data-path="estimaciones.html"><a href="estimaciones.html#estimadores-puntuales"><i class="fa fa-check"></i><b>3.2</b> Estimadores puntuales</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="estimaciones.html"><a href="estimaciones.html#estimador-insesgado-1"><i class="fa fa-check"></i><b>3.2.1</b> Estimador insesgado</a></li>
<li class="chapter" data-level="3.2.2" data-path="estimaciones.html"><a href="estimaciones.html#estimador-eficiente-1"><i class="fa fa-check"></i><b>3.2.2</b> Estimador eficiente</a></li>
<li class="chapter" data-level="3.2.3" data-path="estimaciones.html"><a href="estimaciones.html#error-cuadrático-medio-ecm"><i class="fa fa-check"></i><b>3.2.3</b> Error cuadrático medio (ECM)</a></li>
<li class="chapter" data-level="3.2.4" data-path="estimaciones.html"><a href="estimaciones.html#cota-de-cramer-rao"><i class="fa fa-check"></i><b>3.2.4</b> Cota de Cramer Rao</a></li>
<li class="chapter" data-level="3.2.5" data-path="estimaciones.html"><a href="estimaciones.html#método-de-máxima-verosimilitud"><i class="fa fa-check"></i><b>3.2.5</b> Método de máxima verosimilitud</a></li>
<li class="chapter" data-level="3.2.6" data-path="estimaciones.html"><a href="estimaciones.html#método-de-momentos"><i class="fa fa-check"></i><b>3.2.6</b> Método de momentos</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="estimaciones.html"><a href="estimaciones.html#estimación-por-intervalos-de-confianza"><i class="fa fa-check"></i><b>3.3</b> Estimación por intervalos de confianza</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-la-media-asumiendo-varianza-conocida."><i class="fa fa-check"></i><b>3.3.1</b> Intervalo de confianza para la media, asumiendo varianza conocida.</a></li>
<li class="chapter" data-level="3.3.2" data-path="estimaciones.html"><a href="estimaciones.html#simulación-sobre-la-confiabilidad-de-los-intervalos-de-confianza."><i class="fa fa-check"></i><b>3.3.2</b> Simulación sobre la confiabilidad de los intervalos de confianza.</a></li>
<li class="chapter" data-level="3.3.3" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-sobre-la-diferencia-de-dos-medias-conocida-la-varianza"><i class="fa fa-check"></i><b>3.3.3</b> Intervalo de confianza sobre la diferencia de dos medias, conocida la varianza</a></li>
<li class="chapter" data-level="3.3.4" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-mayor-a-30."><i class="fa fa-check"></i><b>3.3.4</b> Intervalo de confianza para la media y la diferencia de medias con <em>varianza desconocida</em> pero muestra mayor a 30.</a></li>
<li class="chapter" data-level="3.3.5" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-menor-a-30."><i class="fa fa-check"></i><b>3.3.5</b> Intervalo de confianza para la media y la diferencia de medias con varianza desconocida pero muestra menor a 30.</a></li>
<li class="chapter" data-level="3.3.6" data-path="estimaciones.html"><a href="estimaciones.html#intervalos-de-confianza-para-la-diferencia-de-medias-de-datos-pareados"><i class="fa fa-check"></i><b>3.3.6</b> Intervalos de confianza para la diferencia de medias de datos pareados</a></li>
<li class="chapter" data-level="3.3.7" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-proporciones"><i class="fa fa-check"></i><b>3.3.7</b> Intervalo de confianza para proporciones</a></li>
<li class="chapter" data-level="3.3.8" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-diferencia-de-proporciones"><i class="fa fa-check"></i><b>3.3.8</b> Intervalo de confianza para diferencia de proporciones</a></li>
<li class="chapter" data-level="3.3.9" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-la-varianza"><i class="fa fa-check"></i><b>3.3.9</b> Intervalo de confianza para la varianza</a></li>
<li class="chapter" data-level="3.3.10" data-path="estimaciones.html"><a href="estimaciones.html#intervalo-de-confianza-para-el-cociente-de-varianzas"><i class="fa fa-check"></i><b>3.3.10</b> Intervalo de confianza para el cociente de varianzas</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="estimaciones.html"><a href="estimaciones.html#ejercicios"><i class="fa fa-check"></i><b>3.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html"><i class="fa fa-check"></i><b>4</b> Prueba de Hipótesis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#introducción"><i class="fa fa-check"></i><b>4.1</b> Introducción</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#hipótesis-estadística"><i class="fa fa-check"></i><b>4.1.1</b> Hipótesis estadística</a></li>
<li class="chapter" data-level="4.1.2" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#región-de-aceptación-y-región-de-rechazo"><i class="fa fa-check"></i><b>4.1.2</b> Región de aceptación y región de rechazo</a></li>
<li class="chapter" data-level="4.1.3" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#errores-de-tipo-i-y-errores-de-tipo-ii"><i class="fa fa-check"></i><b>4.1.3</b> Errores de tipo I y errores de tipo II</a></li>
<li class="chapter" data-level="4.1.4" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#pruebas-bilaterales"><i class="fa fa-check"></i><b>4.1.4</b> Pruebas bilaterales</a></li>
<li class="chapter" data-level="4.1.5" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#pruebas-unilaterales"><i class="fa fa-check"></i><b>4.1.5</b> Pruebas unilaterales</a></li>
<li class="chapter" data-level="4.1.6" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#pasos-para-la-prueba-hipótesis-estadística"><i class="fa fa-check"></i><b>4.1.6</b> Pasos para la prueba hipótesis estadística</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-media"><i class="fa fa-check"></i><b>4.2</b> Prueba de hipótesis sobre la media</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#con-varianza-conocida"><i class="fa fa-check"></i><b>4.2.1</b> Con varianza conocida</a></li>
<li class="chapter" data-level="4.2.2" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#con-varianza-desconocida"><i class="fa fa-check"></i><b>4.2.2</b> Con varianza desconocida</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-diferencia-de-medias"><i class="fa fa-check"></i><b>4.3</b> Prueba de hipótesis sobre la diferencia de medias</a></li>
<li class="chapter" data-level="4.4" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-proporción"><i class="fa fa-check"></i><b>4.4</b> Prueba de hipótesis sobre la proporción</a></li>
<li class="chapter" data-level="4.5" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-diferencia-de-proporciones"><i class="fa fa-check"></i><b>4.5</b> Prueba de hipótesis sobre la diferencia de Proporciones</a></li>
<li class="chapter" data-level="4.6" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-varianza"><i class="fa fa-check"></i><b>4.6</b> Prueba de hipótesis sobre la varianza</a></li>
<li class="chapter" data-level="4.7" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#prueba-de-hipótesis-sobre-la-igualdad-de-varianzas"><i class="fa fa-check"></i><b>4.7</b> Prueba de hipótesis sobre la igualdad de varianzas</a></li>
<li class="chapter" data-level="4.8" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#test-de-normalidad-aplicados-en-r-bondad-de-ajuste"><i class="fa fa-check"></i><b>4.8</b> Test de normalidad aplicados en R (bondad de ajuste)</a></li>
<li class="chapter" data-level="4.9" data-path="prueba-de-hipótesis.html"><a href="prueba-de-hipótesis.html#tamaño-de-muestra-y-su-relación-con-el-error-de-tipo-i-y-tipo-ii"><i class="fa fa-check"></i><b>4.9</b> Tamaño de muestra y su relación con el error de tipo I y tipo II</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimaciones" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Estimaciones<a href="estimaciones.html#estimaciones" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="inferencia-estadística" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Inferencia estadística<a href="estimaciones.html#inferencia-estadística" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El proceso por el cual, mediante una <strong>muestra estadísticamente seleccionada</strong> se busca describir a la población/universo de la cual esta proviene. Podemos clasificar a la inferencia estadística en:</p>
<ul>
<li><em>Inferencia descriptiva:</em> Tiene el único objetivo de describir a la población mediante la muestra, tradicionalmente se enfoca en <em>estimaciones</em> comunes como; la media, la varianza, total, un porcentaje, diferencia de medias, diferencia de proporciones.</li>
<li>Estimación puntual:</li>
</ul>
<p><span class="math display">\[\hat{\theta}\]</span>
+ Estimación por intervalos:</p>
<p><span class="math display">\[[ \hat{\theta}_{LI},\hat{\theta}_{LS}]\]</span></p>
<ul>
<li>Pruebas de hipótesis:</li>
</ul>
<p><span class="math display">\[\theta=k, \theta&gt;k, \theta&lt;k\]</span>
+ Tamaño de la muestra (<span class="math inline">\(n\)</span>):</p>
<p><span class="math display">\[n=f(U,V(\hat{\theta}),\hat{\theta},\ldots)\]</span></p>
<ul>
<li><em>Inferencia predictiva:</em> Tiene una idea de estudiar; por un lado, la evolución de las estimaciones y sus posibles valores futuros (series de tiempo), por otro lado, le interesa conocer las relaciones (no causales) entre las variables.
<ul>
<li>Series de tiempo</li>
<li>Modelos lineales</li>
<li>Técnicas multivariantes</li>
<li>etc.</li>
</ul></li>
<li><em>Inferencia causal:</em> Tiene el objetivo de medir la relación causal entre variables. <span class="math inline">\(X \rightarrow Y\)</span>
<ul>
<li>Diseños experimentales</li>
<li>Diseños cuasi-experimentales</li>
<li>Modelos estructurales</li>
<li>Etc.</li>
</ul></li>
<li><strong>Inferencia bayesiana</strong></li>
</ul>
</div>
<div id="estimadores-puntuales" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Estimadores puntuales<a href="estimaciones.html#estimadores-puntuales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recordemos que tenemos un universo <span class="math inline">\(U\)</span> de tamaño <span class="math inline">\(N\)</span>.</p>
<p><span class="math display">\[U=\{u_1, u_2,\ldots,u_N\}\]</span>
Donde cada unidad del universo tiene variables (características) asociadas, pensemos en <span class="math inline">\(p\)</span> características.</p>
<p><span class="math display">\[u_i=\{X_{i1},X_{i2}, \ldots , X_{ip}\}\]</span>
Un parámetro es una función sobre el universo y sus variables, lo denotamos por <span class="math inline">\(\theta\)</span></p>
<p><span class="math display">\[\theta=f(U,X)\]</span>
Un estimador se construye a partir de la definición de una <em>estadística</em> (<span class="math inline">\(\Theta\)</span>) y tiene el objetivo de aproximar de la mejor forma a un parámetro.</p>
<p><span class="math display">\[\hat{\theta}\rightarrow \theta\]</span></p>
<p>El estimador <span class="math inline">\(\hat{\theta}\)</span> se construye a partir de una muestra aleatoria (<span class="math inline">\(s\)</span>) de tamaño <span class="math inline">\(n\)</span> obtenida de <span class="math inline">\(U\)</span>.</p>
<p><span class="math display">\[\hat{\theta}=f(s(n),X)\]</span></p>
<blockquote>
<p>Nota:</p>
</blockquote>
<p>Para un parámetro <span class="math inline">\(\theta\)</span>, pueden existir muchos estimadores candidatos:</p>
<p><span class="math display">\[\hat{\Theta}=\{\hat{\theta}_1,\hat{\theta}_2, \hat{\theta}_3,...\}\rightarrow \theta\]</span></p>
<p>la pregunta es ¿Cuál es mejor?. Existen al menos dos criterios:</p>
<div id="estimador-insesgado-1" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Estimador insesgado<a href="estimaciones.html#estimador-insesgado-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math display">\[E[\hat{\theta}]=\theta\]</span></p>
<p>Nota: Un ejemplo de un estimador sesgado es el de la <strong>razón</strong>.</p>
<p><span class="math display">\[R_{y/x}=\frac{t_y}{t_x}=\frac{\mu_y}{\mu_x}\]</span></p>
<p><span class="math display">\[\hat{R}_{y/x}=\frac{\hat{t}_y}{\hat{t}_x}=\frac{\bar{y}}{\bar{x}}\]</span></p>
<p><span class="math display">\[E[\hat{R}_{y/x}]=E\left[\frac{\hat{t}_y}{\hat{t}_x}\right]=E\left[\frac{\bar{y}}{\bar{x}}\right] \neq \frac{t_y}{t_x}\]</span></p>
</div>
<div id="estimador-eficiente-1" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Estimador eficiente<a href="estimaciones.html#estimador-eficiente-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Supongamos que tenemos dos estimadores para <span class="math inline">\(\theta\)</span>, <span class="math inline">\(\hat{\theta}_1\)</span>,
<span class="math inline">\(\hat{\theta}_2\)</span>, el estimador más eficiente entre los dos será quien
tenga el valor más pequeño en su varianza.</p>
<p><span class="math display">\[min(V(\hat{\theta_1}),V(\hat{\theta_2})) \rightarrow \hat{\theta}\]</span></p>
<p>Ejemplo.</p>
<p>Sea el vector <span class="math inline">\(X=\{10,10,20,25,30\}\)</span> de una población con <span class="math inline">\(N=5\)</span>, se
define una muestra de <span class="math inline">\(n=3\)</span> y se busca estimar la media de <span class="math inline">\(X\)</span>: <span class="math inline">\(\mu_x\)</span>.</p>
<p>A partir de los estimadores de la <strong>media</strong> y la <strong>mediana</strong> muestral.
Determinar:</p>
<ul>
<li>Son estimadores insesgados</li>
<li>Cuál estimador es más eficiente</li>
</ul>
<p>Suponga un muestreo sin reposición.</p>
<p>Solución.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="estimaciones.html#cb143-1" aria-hidden="true" tabindex="-1"></a>N<span class="ot">&lt;-</span><span class="dv">5</span></span>
<span id="cb143-2"><a href="estimaciones.html#cb143-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">30</span>)</span>
<span id="cb143-3"><a href="estimaciones.html#cb143-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 10 10 20 25 30</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="estimaciones.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="co">#parámetro</span></span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="estimaciones.html#cb147-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">3</span><span class="co">#muestra</span></span>
<span id="cb147-2"><a href="estimaciones.html#cb147-2" aria-hidden="true" tabindex="-1"></a><span class="fu">choose</span>(<span class="dv">5</span>,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="estimaciones.html#cb149-1" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span><span class="fu">combn</span>(x,<span class="dv">3</span>)</span>
<span id="cb149-2"><a href="estimaciones.html#cb149-2" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
## [1,]   10   10   10   10   10   10   10   10   10
## [2,]   10   10   10   20   20   25   20   20   25
## [3,]   20   25   30   25   30   30   25   30   30
##      [,10]
## [1,]    20
## [2,]    25
## [3,]    30</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="estimaciones.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co">#distribución muestral de la media muestral</span></span>
<span id="cb151-2"><a href="estimaciones.html#cb151-2" aria-hidden="true" tabindex="-1"></a>dmedia<span class="ot">&lt;-</span><span class="fu">apply</span>(s,<span class="dv">2</span>,mean)</span>
<span id="cb151-3"><a href="estimaciones.html#cb151-3" aria-hidden="true" tabindex="-1"></a>dmedia</span></code></pre></div>
<pre><code>##  [1] 13.33333 15.00000 16.66667 18.33333 20.00000
##  [6] 21.66667 18.33333 20.00000 21.66667 25.00000</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="estimaciones.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co">#distribución muestral de la mediana muestral</span></span>
<span id="cb153-2"><a href="estimaciones.html#cb153-2" aria-hidden="true" tabindex="-1"></a>dmediana<span class="ot">&lt;-</span><span class="fu">apply</span>(s,<span class="dv">2</span>,median)</span>
<span id="cb153-3"><a href="estimaciones.html#cb153-3" aria-hidden="true" tabindex="-1"></a>dmediana</span></code></pre></div>
<pre><code>##  [1] 10 10 10 20 20 25 20 20 25 25</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="estimaciones.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Son estimadores insesgados</span></span>
<span id="cb155-2"><a href="estimaciones.html#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="co">#media</span></span>
<span id="cb155-3"><a href="estimaciones.html#cb155-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(dmedia<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>)) <span class="co"># E[]</span></span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="estimaciones.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dmedia)</span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="estimaciones.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co">#media</span></span>
<span id="cb159-2"><a href="estimaciones.html#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(dmediana<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>)) <span class="co"># E[]</span></span></code></pre></div>
<pre><code>## [1] 18.5</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="estimaciones.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dmediana)</span></code></pre></div>
<pre><code>## [1] 18.5</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="estimaciones.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="co">#parámetro media poblacional</span></span>
<span id="cb163-2"><a href="estimaciones.html#cb163-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="estimaciones.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cuál estimador es más eficiente</span></span>
<span id="cb165-2"><a href="estimaciones.html#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((dmedia<span class="sc">-</span><span class="fu">mean</span>(dmedia))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span><span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>) <span class="co"># media muestral</span></span></code></pre></div>
<pre><code>## [1] 10.66667</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="estimaciones.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((dmediana<span class="sc">-</span><span class="fu">mean</span>(dmediana))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span><span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>) <span class="co"># mediana muestral</span></span></code></pre></div>
<pre><code>## [1] 35.25</code></pre>
<p>Para este ejercicio, la media muestral es insesgado y más eficiente que la mediana muestral, como un estimador de la media poblacional.</p>
<blockquote>
<p>Nota</p>
</blockquote>
<p>Los principales problemas de estimación ocurren con frecuencia para estimar:</p>
<ul>
<li>El promedio o media de una población <span class="math inline">\(\mu\)</span></li>
</ul>
<p><span class="math display">\[\mu_X=\frac{\sum_U X_i}{N}\]</span></p>
<ul>
<li>La varianza poblacional <span class="math inline">\(\sigma^2\)</span></li>
</ul>
<p><span class="math display">\[\sigma^2=\frac{\sum_U (X_i-\mu_X)^2}{N}\]</span></p>
<ul>
<li>La proporción de una característica en la población <span class="math inline">\(P\)</span></li>
</ul>
<p><span class="math display">\[P_A=\frac{\#A}{N}=\frac{\sum_{U} X_i}{N}; \quad \{X_i=1, \quad i \in A, X_i=0,\quad eoc\}\]</span></p>
<ul>
<li>La diferencia de medias de dos poblaciones</li>
</ul>
<p><span class="math display">\[\mu_1-\mu_2\]</span></p>
<ul>
<li>La diferencia de proporciones de dos poblaciones</li>
</ul>
<p><span class="math display">\[P_1-P_2\]</span>
- El cociente de varianzas de dos poblaciones</p>
<p><span class="math display">\[\sigma_1/\sigma_2\]</span></p>
<p>Estimaciones puntuales razonables de estos parámetros son las
siguientes:</p>
<ul>
<li>Para <span class="math inline">\(\mu_x\)</span>, la estimación es la media muestral: <span class="math inline">\(\hat{\mu_x}=\bar{X}\)</span></li>
</ul>
<p><span class="math display">\[\bar{x}=\frac{\sum_s X_i}{n}\]</span>
- Para <span class="math inline">\(\sigma^2\)</span>, la estimación es la varianza muestral <span class="math inline">\(S^2\)</span>,</p>
<p><span class="math display">\[S^2=\frac{\sum_s (X_i-\bar{X})^2}{n-1}\]</span></p>
<ul>
<li>Para <span class="math inline">\(P\)</span>, la estimación es <span class="math inline">\(\hat{P}\)</span>, la proporción muestral</li>
</ul>
<p><span class="math display">\[\hat{P}_A=\frac{\#_sA}{n}=\frac{\sum_{s} X_i}{n}; \quad \{X_i=1, \quad i \in A, X_i=0,\quad eoc\}\]</span>
- Para <span class="math inline">\(\mu_1-\mu_2\)</span>, la diferencia entre las medias de las muestras de dos muestras aleatorias <em>independientes</em>.</p>
<p><span class="math display">\[\hat{\mu_1}-\hat{\mu}_2=\bar{X}_1-\bar{X}_2\]</span>
- Para <span class="math inline">\(P_1-P_2\)</span>, la diferencia entre las proporciones de las muestras de dos muestras aleatorias <em>independientes</em>.</p>
<p><span class="math display">\[\hat{P_1}-\hat{P}_2\]</span>
- Para el cociente de varianzas <span class="math inline">\(\sigma_1/\sigma_2\)</span> un estimador razonables es:</p>
<p><span class="math display">\[\hat{S}_1/\hat{S}_2\]</span></p>
<blockquote>
<p>Ejemplo,</p>
</blockquote>
<p>Suponga que <span class="math inline">\(X\)</span> es una variable aleatoria con media <span class="math inline">\(\mu_x\)</span> y varianza <span class="math inline">\(\sigma^2_x\)</span>. Sea <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span>.</p>
<p><strong>DEMOSTRAR</strong> que la media muestral <span class="math inline">\(\bar{X}\)</span> y la varianza muestral <span class="math inline">\(S^2\)</span> son estimadores insesgados de <span class="math inline">\(\mu_x\)</span> y <span class="math inline">\(\sigma^2_x\)</span>, respectivamente.</p>
<p>Como información; <span class="math inline">\(E[X]=\mu\)</span>,</p>
<p><span class="math display">\[V(X)=\sigma^2=E[X^2]-E[X]^2\]</span>.</p>
<p>Solución,</p>
<p><span class="math display">\[E[\bar{X}]=E\left[\frac{\sum_s X_i}{n} \right]=\frac{1}{n}\left(\sum_s E[X_i]\right)=\frac{1}{n}\left(\sum_{i=1}^n \mu\right)=\mu \]</span>
Así,</p>
<p><span class="math display">\[V(\bar{X})=\frac{\sigma^2}{n}=E[\bar{X}^2]-E[\bar{X}]^2=E[\bar{X}^2]-\mu^2\]</span></p>
<p><span class="math display">\[E[S^2]=E\left[\frac{\sum_s (X_i-\bar{X})^2}{n-1} \right]=\frac{1}{n-1} E\left[\sum_s (X_i^2-2X_i \bar{X}+\bar{X}^2) \right]=\]</span></p>
<p><span class="math display">\[=\frac{1}{n-1}E\left[\sum_s X_i^2-2\bar{X} \sum_sX_i +n\bar{X}^2 \right]= \]</span></p>
<p><span class="math display">\[=\frac{1}{n-1}E\left[\sum_s X_i^2-2\bar{X}n\frac{\sum_s X_i}{n}  +n\bar{X}^2 \right]=\]</span>
<span class="math display">\[=\frac{1}{n-1}E\left[\sum_s X_i^2-2n\bar{X}^2  +n\bar{X}^2 \right]=\frac{1}{n-1}E\left[\sum_s X_i^2-n\bar{X}^2\right]=\]</span></p>
<p><span class="math display">\[=\frac{1}{n-1}\left(\sum_s E[X_i^2]-nE[\bar{X}^2] \right)= \alpha\]</span>
Notar</p>
<p><span class="math inline">\(\sigma^2=E[X^2]-E[X]^2=E[X^2]-\mu^2\)</span> para un <span class="math inline">\(X_i\)</span>,
<span class="math inline">\(\sigma^2=E[X_i^2]-E[X_i]^2=E[X_i^2]-\mu^2\)</span>, entonces,
<span class="math inline">\(E[X_i^2]=\sigma^2+\mu^2\)</span>. Por otro lado
<span class="math inline">\(E[\bar{X}^2]=\frac{\sigma^2}{n}+\mu^2\)</span>, Así:</p>
<p><span class="math display">\[\alpha=\frac{1}{n-1}\left[\sum_s (\sigma^2+\mu^2) -n \left(\frac{\sigma^2}{n}+\mu^2 \right) \right]=\]</span>
<span class="math display">\[=\frac{1}{n-1}\left[ n \sigma^2+n\mu^2 -\sigma^2-n\mu^2  \right]=\frac{\sigma^2(n-1)}{n-1}=\sigma^2\]</span></p>
</div>
<div id="error-cuadrático-medio-ecm" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Error cuadrático medio (ECM)<a href="estimaciones.html#error-cuadrático-medio-ecm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Este se define para un estimador como:</p>
<p><span class="math display">\[ECM(\hat{\theta})=E\left[(\hat{\theta}-\theta)^2\right]\]</span></p>
<p>Recordar que</p>
<p><span class="math display">\[V(\hat{\theta})=E\left[(\hat{\theta}-E[\hat{\theta}])^2\right]\]</span></p>
<p><span class="math display">\[ECM(\hat{\theta})=E\left[\left[(\hat{\theta}-E[\hat{\theta}])-(\theta-E[\hat\theta]) \right]^2\right]=E\left[(\hat{\theta}-E[\hat{\theta}])^2-2(\hat{\theta}-E[\hat{\theta}])(\theta-E[\hat\theta])+ (\theta-E[\hat\theta])^2 \right]=\]</span></p>
<p><span class="math display">\[=E[(\hat{\theta}-E[\hat{\theta}])^2]-2(\theta-E[\hat\theta])E\left[\hat{\theta}-E[\hat{\theta}]\right]+E[(\theta-E[\hat\theta])^2]=V(\hat\theta)=V(\hat{\theta})+E[(\theta-E[\hat\theta])^2]=\]</span></p>
<p><span class="math display">\[=V(\hat{\theta})+sesgo(\hat\theta)^2\]</span></p>
</div>
<div id="cota-de-cramer-rao" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Cota de Cramer Rao<a href="estimaciones.html#cota-de-cramer-rao" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Es posible obtener una cota inferior de la varianza de todos los estimadores (<span class="math inline">\(\hat{\theta}_1, \hat{\theta}_2,\ldots\)</span>) insesgados de <span class="math inline">\(\theta\)</span>. Sea <span class="math inline">\(\hat{\theta}\)</span> un estimador insesgado del parámetro <span class="math inline">\(\theta\)</span>, basado en una muestra aleatoria de <span class="math inline">\(n\)</span> observaciones, y considérese que <span class="math inline">\(f(x,\theta)\)</span> denota la función de distribución de probabilidades de una variable aleatoria <span class="math inline">\(X\)</span>. Entonces una cota inferior en la varianza de <span class="math inline">\(\hat{\theta}\)</span> es:</p>
<p><span class="math display">\[V(\hat{\theta})\geq\frac{1}{nE\left\{ \left[\frac{d}{d\theta }ln f(X,\theta) \right]^2 \right\}}\]</span></p>
<p>Esta desigualdad se denomina <em>cota de Cramer Rao</em>. Si un estimador insesgado <span class="math inline">\(\hat{\theta}\)</span> satisface la desigualdad, se tratará del estimador insesgado de varianza mínima de <span class="math inline">\(\theta\)</span>.</p>
<blockquote>
<p>Ejemplo,</p>
</blockquote>
<p>Demostrar que la media muestral <span class="math inline">\(\bar{x}\)</span> es el estimador insesgado de varianza mínima de la media de una distribución normal con varianza conocida.</p>
<p>Sea <span class="math inline">\(X\sim N(\mu,\sigma^2)\)</span>, sabemos <span class="math inline">\(E[\bar{x}]=\mu\)</span></p>
<p><span class="math display">\[f(X,\mu)=\frac{1}{\sqrt{2\pi} \sigma}e^{-\frac{1}{2}\left(\frac{X-\mu}{\sigma}\right)^2}\]</span>
<span class="math display">\[ln f(X,\mu)=ln\left( \frac{1}{\sqrt{2\pi} \sigma}e^{-\frac{1}{2}\left(\frac{X-\mu}{\sigma}\right)^2} \right)=-ln\left( \sqrt{2\pi} \sigma \right) -\frac{1}{2}\left(\frac{X-\mu}{\sigma}\right)^2\]</span></p>
<p><span class="math display">\[E\left\{\left[ \frac{d}{d\mu} ln f(X,\mu)\right]^2 \right\}=E\left\{ \left[ \frac{(X-\mu)}{\sigma^2} \right]^2\right\} =E\left[\frac{(X-\mu)^2}{\sigma^4} \right]=\frac{E[(X-\mu)^2]}{\sigma^4}=\]</span>
<span class="math display">\[=\frac{\sigma^2}{\sigma^4}=\frac{1}{\sigma^2}\]</span></p>
<p>Finalmente, para la cota de Cramer-Rao</p>
<p><span class="math display">\[V(\bar{x})\geq \frac{1}{\frac{n}{\sigma^2}}=\frac{\sigma^2}{n}=V(\bar{x})\]</span></p>
<p>Tarea:
- Para la varianza muestral <span class="math inline">\(S^2\)</span>, encontrar la cota de cramer Rao, suponiendo media conocida y distribución normal.
- Suponer que <span class="math inline">\(x\sim exp(\lambda)\)</span>, si el objetivo es estimar <span class="math inline">\(\lambda\)</span> encontrar la cota de cramer Rao para <span class="math inline">\(\lambda\)</span>.</p>
</div>
<div id="método-de-máxima-verosimilitud" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Método de máxima verosimilitud<a href="estimaciones.html#método-de-máxima-verosimilitud" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(X\)</span> es una va, con distribución <span class="math inline">\(f(X,\theta)\)</span>, donde
<span class="math inline">\(\theta\)</span> es un parámetro desconocido. Sean <span class="math inline">\(X_1, X_2,\ldots, X_n\)</span> va.
iid. como <span class="math inline">\(X\)</span>, la muestra de tamaño <span class="math inline">\(n\)</span>. La función de probabilidad de
las <span class="math inline">\(n\)</span> va. se escribe como:</p>
<p><span class="math display">\[f(X_1,X_2, \ldots,X_n,\theta)=f(X_1,\theta)*f(X_2,\theta)*\ldots*f(X_n,\theta)=L(\theta)\]</span>
El estimador de máxima verosimilitud de <span class="math inline">\(\theta\)</span> es el valor que
maximiza la función de probabilidad <span class="math inline">\(L(\theta)\)</span>.</p>
<p>Pasos para obtener el estimador de máxima verosimilitud para un
parámetro <span class="math inline">\(\theta\)</span></p>
<ol style="list-style-type: decimal">
<li>Obtener <span class="math inline">\(L(\theta)\)</span></li>
<li>Calcular <span class="math inline">\(ln [L(\theta)]\)</span></li>
<li>Resolver la ecuación:</li>
</ol>
<p><span class="math display">\[\frac{d}{d\theta} ln [L(\theta)]=0\]</span></p>
<p>En el caso de que tengamos más de un parámetro, los pasos son:</p>
<ol style="list-style-type: decimal">
<li>Obtener
<span class="math inline">\(L(\theta_1,\theta_2,\ldots)=f(X_1,\theta_1,\theta_2,\ldots)*\ldots*f(X_n,\theta_1,\theta_2,\ldots)\)</span></li>
<li>Calcular <span class="math inline">\(ln [L(\theta_1,\theta_2,\ldots)]\)</span></li>
<li>Resolver el sistema de ecuaciones:</li>
</ol>
<p><span class="math display">\[\frac{\partial }{\partial \theta_1} ln [L(\theta_1,\theta_2,\ldots)]=0\]</span>
<span class="math display">\[\frac{\partial }{\partial \theta_2} ln [L(\theta_1,\theta_2,\ldots)]=0\]</span>
<span class="math display">\[\vdots\]</span></p>
<p><span class="math display">\[\frac{\partial }{\partial \theta_p} ln [L(\theta_1,\theta_2,\ldots)]=0\]</span></p>
<p>Ejemplos</p>
<p>Para el caso discreto, sea <span class="math inline">\(x\)</span> una variable aleatoria con función de probabilidad:</p>
<p><span class="math display">\[\pi(x)=P(X=x)=\theta (1-\theta)^{x-1}; \quad x=1,2,3,\ldots; \quad 0\leq\theta\leq1\]</span>
Encontrar al estimador de máxima verosimilitud de <span class="math inline">\(\theta\)</span></p>
<p>Solución,</p>
<p>Sea <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> una muestra aleatoria, donde las <span class="math inline">\(X_i\)</span> son iid. Así:</p>
<p><span class="math display">\[\pi(x_i)=P(X_i=x_i)=\theta (1-\theta)^{x_i-1}; \quad x_i=1,2,3,\ldots; \quad 0\leq\theta\leq1\]</span></p>
<p><span class="math display">\[L(\theta)=\prod_{i=1}^n \theta (1-\theta)^{x_i-1}=\theta^n (1-\theta)^{\sum_s x_i - n}\]</span></p>
<p><span class="math display">\[ln (L (\theta))=ln \left(\theta^n (1-\theta)^{\sum_s x_i - n} \right)=n ln (\theta)+\left(\sum_s x_i -n\right) ln(1-\theta)\]</span></p>
<p><span class="math display">\[\frac{d}{d \theta} ln(L(\theta))=\frac{n}{\theta}-\left(\sum_s x_i -n\right)\frac{1}{1-\theta}=0\]</span></p>
<p><span class="math display">\[\frac{n}{\theta}=\frac{\left(\sum_s x_i -n\right)}{1-\theta}\rightarrow n-n\theta=\theta \sum_s x_i-n\theta\]</span>
<span class="math display">\[n=\theta \sum_s x_i\]</span></p>
<p><span class="math display">\[\hat{\theta}=\frac{n}{\sum_s x_i}=\frac{1}{\bar{x}}\]</span></p>
<p>Sea <span class="math inline">\(X\sim Bernoulli(p)\)</span>, la función de probabilidad es:</p>
<p><span class="math display">\[P(X=x)=\pi(x)=p^x (1-p)^{1-x} \quad ; x=\{0,1\}\]</span></p>
<p>Si <span class="math inline">\(p\)</span> es el parámetro de interés que se busca estimar, ¿qué forma tendrá el estimador de máxima verosimilitud?</p>
<p>Solución,</p>
<p>Supongamos que se extrae una muestra de tamaño <span class="math inline">\(n\)</span>, así:</p>
<p><span class="math display">\[L(p)=f(X_1,p)*f(X_2,p)*\ldots*f(X_n,p)=p^{x_1} (1-p)^{1-x_1}*p^{x_2} (1-p)^{1-x_2}*\ldots*p^{x_n} (1-p)^{1-x_n}\]</span></p>
<p><span class="math display">\[L(p)=p^{\sum_{i=1}^n x_i}*(1-p)^{n-\sum_{i=1}^n x_i}\]</span></p>
<p><span class="math display">\[ln[ L(p)]= \sum_{i=1}^n x_i ln(p)+\left(n-\sum_{i=1}^n x_i \right) ln(1-p) \]</span></p>
<p><span class="math display">\[\frac{d}{dp}ln[ L(p)]= \frac{\sum_{i=1}^n x_i}{p}-\frac{\left(n-\sum_{i=1}^n x_i\right)}{1-p}=0\]</span></p>
<p><span class="math display">\[ \frac{\sum_{i=1}^n x_i}{p}-\frac{\left(n-\sum_{i=1}^n x_i\right)}{1-p}=0\]</span></p>
<p><span class="math display">\[\hat{p}_{mv}=\frac{\sum_{i=1}^n x_i}{n}\]</span></p>
<p>Ejemplo, Sea <span class="math inline">\(X_1, X_2, \ldots,X_n\)</span>, va iid, tal que
<span class="math inline">\(X_i\sim Poisson(\lambda)\)</span>. Encontrar el estimador de <span class="math inline">\(\lambda\)</span>
empleando el método de máxima verosimilitud.</p>
<p>Solución, recordar que si <span class="math inline">\(X\sim Poisson(\lambda)\)</span></p>
<p><span class="math display">\[\pi(x)=P(X=x)=\frac{e^{-\lambda} \lambda ^x}{x!}; \quad X=\{0,1,2\ldots\}\]</span></p>
<p><span class="math display">\[L(\lambda)=\pi(X_1,\lambda)*\pi(X_2,\lambda)*\ldots*\pi(X_n,\lambda)\]</span></p>
<p><span class="math display">\[L(\lambda)=\frac{e^{-\lambda} \lambda ^{x_1}}{x_1!}*\frac{e^{-\lambda} \lambda ^{x_2}}{x_2!}*\ldots*\frac{e^{-\lambda} \lambda ^{x_n}}{x_n!}\]</span></p>
<p><span class="math display">\[L(\lambda)=\prod_{i=1}^n \frac{e^{-\lambda} \lambda ^{x_i}}{x_i!}=\frac{e^{-n\lambda}\lambda^{\sum_{i=1}^n x_i}}{\prod_{i=1}^n x_i!}\]</span>
<span class="math display">\[ln [L(\lambda)]=-n\lambda+\sum_{i=1}^n x_i ln \lambda - ln \prod_{i=1}^n x_i!\]</span>
<span class="math display">\[\frac{d}{d\lambda}ln [L(\lambda)]=-n+\frac{\sum_{i=1}^n x_i}{\lambda}=0\]</span></p>
<p><span class="math display">\[\hat{\lambda}=\frac{\sum_{i=1}^n x_i}{n}\]</span></p>
<p>Ejemplo, Sea <span class="math inline">\(X_1, X_2, \ldots,X_n\)</span>, va iid, tal que
<span class="math inline">\(X_i\sim exp(\lambda)\)</span>. Encontrar el estimador de <span class="math inline">\(\lambda\)</span> empleando el
método de máxima verosimilitud.</p>
<p>Solución, recordar que si <span class="math inline">\(X\sim exp(\lambda)\)</span> su función de densidad es
dada por:</p>
<p><span class="math display">\[f(x)=\lambda e^{-\lambda x}; \quad x\geq0\]</span></p>
<p><span class="math display">\[L(\lambda)=\prod_{i=1}^n \lambda e^{-\lambda x_i}=\lambda^n e^{-\lambda \sum_{i=1}^n x_i}\]</span>
<span class="math display">\[ln [L(\lambda)]=n ln \lambda-\lambda \sum_{i=1}^n x_i\]</span>
<span class="math display">\[\frac{d}{d\lambda}ln [L(\lambda)]=\frac{n}{\lambda}-\sum_{i=1}^n x_i=0\]</span>
<span class="math display">\[\hat{\lambda}=\frac{1}{\frac{\sum_{i=1}^n x_i}{n}}=\frac{1}{\bar{X}}\]</span></p>
<p>Ejemplo, Sea <span class="math inline">\(X_1, X_2, \ldots,X_n\)</span>, va iid, tal que
<span class="math inline">\(X_i\sim N(\mu,\sigma^2)\)</span> ambos parámetros desconocidos. Encontrar los
estimadores de máxima verosimilitud para <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Solución, recordar si <span class="math inline">\(X\sim N(\mu, \sigma^2)\)</span> su función de densidad es
dada por:</p>
<p><span class="math display">\[f(X)=\frac{1}{\left(2\pi \sigma^2 \right)^{1/2} }e^{-\frac{1}{2}\frac{\left(x-\mu\right)^2}{\sigma^2}}\]</span>
<span class="math display">\[L(\mu,\sigma^2)=\prod_{i=1}^n \frac{1}{\left(2\pi \sigma^2 \right)^{1/2} }e^{-\frac{1}{2}\frac{\left(x_i-\mu\right)^2}{\sigma^2}}=\frac{1}{\left(2\pi \sigma^2 \right)^{n/2} }e^{-\frac{1}{2 \sigma^2}\sum_{i=1}^n \left(x_i-\mu\right)^2}\]</span>
<span class="math display">\[ln[L(\mu,\sigma^2)]=-\frac{n}{2}ln (2\pi \sigma^2)-\frac{1}{2 \sigma^2}\sum_{i=1}^n \left(x_i-\mu\right)^2\]</span>
<span class="math display">\[\frac{\partial}{\partial \mu} ln[L(\mu,\sigma^2)]=\frac{1}{\sigma^2} \sum_{i=1}^n \left(x_i-\mu\right)=0\]</span></p>
<p><span class="math display">\[\frac{\partial}{\partial \sigma^2} ln[L(\mu,\sigma^2)]=-\frac{n}{2 \sigma^2}+\frac{1}{2 \sigma^4}\sum_{i=1}^n \left(x_i-\mu\right)^2=0\]</span>
<span class="math display">\[\sum_{i=1}^n x_i - n\mu=0\]</span>
<span class="math display">\[\hat{\mu}=\frac{\sum_{i=1}^n x_i}{n}=\bar{X}\]</span></p>
<p><span class="math display">\[\hat{\sigma}^2=\frac{\sum_{i=1}^n \left(x_i-\bar{X}\right)^2}{n}\]</span></p>
</div>
<div id="método-de-momentos" class="section level3 hasAnchor" number="3.2.6">
<h3><span class="header-section-number">3.2.6</span> Método de momentos<a href="estimaciones.html#método-de-momentos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Este método fue desarrollado por 1894 por Pearson, a diferencia del
método de máxima verosimilitud que fue ampliamente utilizado por Fisher
a partir 1912.</p>
<p>Recordar que para una variable aleatoria, los momentos respecto el
origen son:</p>
<ul>
<li>Primer Momento: <span class="math inline">\(\mu_1=E[X]=\int x f(x) dx\)</span></li>
<li>Segundo Momento: <span class="math inline">\(\mu_2=E[X^2]=\int x^2 f(x) dx\)</span></li>
<li>k-ésimo momento: <span class="math inline">\(\mu_k=E[X^k]\)</span></li>
</ul>
<p>Sea <span class="math inline">\(X_1, X_2, \ldots ,X_n\)</span> una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de una
va <span class="math inline">\(X\)</span>, definamos los primeros <span class="math inline">\(k\)</span> momentos de la muestra respecto al
origen como:</p>
<ul>
<li>Primer momento:</li>
</ul>
<p><span class="math display">\[m_1=\frac{\sum_{i=1}^n x_i}{n}\]</span></p>
<ul>
<li>Segundo momento:</li>
</ul>
<p><span class="math display">\[m_2=\frac{\sum_{i=1}^n x^2_i}{n}\]</span></p>
<ul>
<li>k-ésimo momento:</li>
</ul>
<p><span class="math display">\[m_k=\frac{\sum_{i=1}^n x^k_i}{n}; \quad k=1,2,\ldots \]</span></p>
<p>Los momentos <span class="math inline">\(\mu_k\)</span> de la población serán funciones de los parámetros
desconocidos <span class="math inline">\(\theta\)</span>. Al igualar estos momentos muestrales con los
poblaciones vamos a poder construir un sistema de ecuaciones de cuantas
incógnitas se defina con la distribución de <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[\mu_1=E[x]=m_1=\frac{\sum_s x_i}{n}\]</span>
<span class="math display">\[\mu_2=E[x^2]=m_2=\frac{\sum_s x_i^2}{n}\]</span></p>
<p><span class="math display">\[\mu_k=E[x^k]=m_k=\frac{\sum_s x_i^k}{n}\]</span></p>
<p>Ejemplo, Sea <span class="math inline">\(X_1, X_2, \ldots,X_n\)</span>, va iid, tal que
<span class="math inline">\(X_i\sim exp(\lambda)\)</span>. Encontrar el estimador de <span class="math inline">\(\lambda\)</span> empleando el
método de momentos.</p>
<p>Solución, recordar que si <span class="math inline">\(X\sim exp(\lambda)\)</span> su función de densidad es
dada por:</p>
<p><span class="math display">\[f(x)=\lambda e^{-\lambda x}; \quad x\geq0\]</span> <span class="math display">\[E[X]=m_1\]</span>
<span class="math display">\[E[X]=\int_0^\infty x\lambda e^{-\lambda x}dx=\frac{1}{\lambda}\]</span></p>
<p>Igualando los momentos:</p>
<p><span class="math display">\[\frac{1}{\lambda}=\frac{\sum_s x_i}{n}\]</span></p>
<p><span class="math display">\[\hat{\lambda}= \frac{1}{\frac{\sum_s x_i}{n}}=\frac{1}{\bar{X}}\]</span></p>
<p>Ejercicio, Sea <span class="math inline">\(X\)</span> una va geométrica con parámetro <span class="math inline">\(p\)</span>, encuentre un
estimador de <span class="math inline">\(p\)</span> mediante el método de momentos y el método de máxima
verosimilitud. En base a una muestra aleatoria de tamaño <span class="math inline">\(n\)</span></p>
<p>Recordar que si <span class="math inline">\(X\sim G(p)\)</span>, entonces su distribución de probabilidades
es:</p>
<p><span class="math display">\[\pi(x)=P(X=x)=(1-p)^x p; \quad x=\{0,1,2,\dots\} \]</span></p>
<p>Recordar que <span class="math inline">\(E[X]=\frac{1-p}{p}\)</span>, por el método de momentos:</p>
<p><span class="math display">\[\frac{1-p}{p}=\bar{X}\]</span></p>
<p><span class="math display">\[\hat{p}=\frac{1}{\bar{X}+1}\]</span> Por el método de máxima verosimilitud.</p>
<p><span class="math display">\[L(p)=\prod_{i=1}^n (1-p)^{x_i} p=(1-p)^{\sum_s x_i} p^n\]</span>
<span class="math display">\[ln [L(p)]=\sum_s x_i ln (1-p)+n ln(p)\]</span></p>
<p><span class="math display">\[\frac{d}{dp}ln [L(p)]=-\frac{\sum_s x_i}{1-p}+\frac{n}{p}=0\]</span>
<span class="math display">\[\hat{p}=\frac{1}{\bar{X}+1}\]</span></p>
<p>Ejercicio,
Sea <span class="math inline">\(X\)</span> una normal con parámetro <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma^2\)</span>, encuentre un estimador de <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma^2\)</span> mediante el método de momentos. En base a una muestra aleatoria de tamaño <span class="math inline">\(n\)</span></p>
<p><span class="math display">\[E[X]=m_1\rightarrow \mu=\bar{X}\]</span>
<span class="math display">\[E[X^2]=m_2\rightarrow E[X^2]=\frac{\sum_s x_i^2}{n}\rightarrow (\alpha)\]</span></p>
<p>Recordar que:</p>
<p><span class="math display">\[\sigma^2=E[X^2]-E[X]^2=E[X^2]-\mu^2 \approx E[X^2]-\bar{X}^2\]</span></p>
<p>Para <span class="math inline">\((\alpha)\)</span></p>
<p><span class="math display">\[\sigma^2+\bar{X}^2=\frac{\sum_s x_i^2}{n}\rightarrow \hat{\sigma}^2=\frac{\sum_s x_i^2}{n}-\bar{X}^2\]</span></p>
<p>Tarea, sea <span class="math inline">\(X\)</span> una va con función de densidad:</p>
<p><span class="math display">\[f(x)=\frac{2(\theta-x)}{\theta^2}; \quad 0\leq x\leq \theta; \quad \theta&gt;0\]</span></p>
<ul>
<li>Verificar que es una función de densidad</li>
<li>Encontrar el estimador de <span class="math inline">\(\theta\)</span> por el método de momentos y máxima verosimilitud</li>
<li>Verificar si el estimador por método de momentos y máxima verosimilitud es insesgado.</li>
</ul>
<p>Solución</p>
<ul>
<li>Verificar que es una función de densidad</li>
</ul>
<p><span class="math display">\[1=\int_{Rx} f(x)dx=\int_{0}^\theta \frac{2(\theta-x)}{\theta^2} dx=\frac{2}{\theta^2}(-1) \frac{(\theta-x)^2}{2}/_0^\theta\]</span><br />
<span class="math display">\[\frac{1}{\theta^2}(-1)\left(0^2-\theta^2 \right)=1 \]</span></p>
<ul>
<li>Encontrar el estimador de <span class="math inline">\(\theta\)</span> por el método de momentos y máxima verosimilitud</li>
</ul>
<p>Suponer que tenemos una muestra aleatoria de tamaño <span class="math inline">\(n\)</span>, con las va <span class="math inline">\(x_1,x_2,\ldots,x_n\)</span> siente estas variables iid.</p>
<p>Para el método de momentos se requiere resolver:</p>
<p><span class="math display">\[E[X]=m_1; \quad E[X]=\bar{X}\]</span>
Se requiere calcular <span class="math inline">\(E[X]\)</span></p>
<p><span class="math display">\[E[X]=\int_{Rx}x f(x)dx=\int_0^\theta x \frac{2(\theta-x)}{\theta^2} dx=\frac{\theta}{3}\]</span>
Entonces,</p>
<p><span class="math display">\[\frac{\theta}{3}=\bar{X}\quad \rightarrow \hat{\theta}=3\bar{X}\]</span></p>
<p>Para el método de máxima verosimilitud, sabemos que:</p>
<p><span class="math display">\[f(x_i,\theta)=\frac{2(\theta-x_i)}{\theta^2}\]</span></p>
<p><span class="math display">\[L(\theta)=\prod_{i=1}^n \frac{2(\theta-x_i)}{\theta^2}=\frac{2^n}{\theta^{2n}}\prod_{i=1}^n\left( \theta -  x_i\right) \]</span></p>
<p><span class="math display">\[ln(L(\theta))=ln\left[\frac{2^n}{\theta^{2n}}\prod_{i=1}^n\left( \theta -  x_i\right)\right]=n ln (2)-2n ln(\theta)+ln (\prod_{i=1}^n\left( \theta -  x_i\right))\]</span></p>
<p><span class="math display">\[=n ln (2)-2n ln(\theta)+\sum_{i=1}^n ln (\theta-x_i)\]</span></p>
<p><span class="math display">\[\frac{d ln(L(\theta))}{d\theta}=-\frac{2n}{\theta}+\sum_{i=1}^n \frac{1}{\theta-x_i}=0\]</span>
<span class="math display">\[\sum_{i=1}^n \frac{1}{\theta-x_i}=\frac{2n}{\theta} \rightarrow\quad \sum_{i=1}^n \frac{\theta}{\theta-x_i}=\sum_{i=1}^n 2\rightarrow \frac{\theta}{\theta-x_i}=2\]</span></p>
<p><span class="math display">\[\theta=2x_i \rightarrow \sum_s \theta = 2 \sum_s x_i\]</span>
<span class="math display">\[\hat{\theta}=2\bar{X}\]</span></p>
<ul>
<li>Verificar si el estimador por método de momentos y máxima verosimilitud es insesgado.</li>
</ul>
<p>Para el método de momentos:</p>
<p><span class="math display">\[E[\hat{\theta}]=E[3\bar{X}]=3E\left[\frac{\sum_s x_i}{n}\right]=\frac{3}{n}\sum_s E[x_i]=\frac{3}{n}\sum_s \frac{\theta}{3}=\]</span>
<span class="math display">\[=\frac{3n\theta}{n3}=\theta\]</span></p>
<p>Para el método de máxima verosimilitud</p>
<p><span class="math display">\[E[\hat{\theta}]=E[2\bar{X}]=2E\left[\frac{\sum_s x_i}{n}\right]=\frac{2}{n}\sum_s E[x_i]=\frac{2}{n}\sum_s \frac{\theta}{3}=\frac{2}{3}\theta\]</span></p>
</div>
</div>
<div id="estimación-por-intervalos-de-confianza" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Estimación por intervalos de confianza<a href="estimaciones.html#estimación-por-intervalos-de-confianza" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para construir un intervalo de confianza del parámetro desconocido
<span class="math inline">\(\theta\)</span>, se debe encontrar dos estadísticas <span class="math inline">\(L\)</span> y <span class="math inline">\(U\)</span> tales que:</p>
<p><span class="math display">\[P(L\leq\theta\leq U)=1-\alpha\]</span></p>
<p>El intervalo <span class="math inline">\(L\leq\theta\leq U\)</span> se llama intervalo de confianza del <span class="math inline">\(100*(1-\alpha)\)</span> (Porcentaje de confiabilidad del intervalo). A <span class="math inline">\(L\)</span> se lo conoce como límite inferior y <span class="math inline">\(U\)</span> como límite superior.</p>
<p>La interpretación del intervalo de confianza es que si se coleccionan
muchas muestras aleatorias y se calcula un intervalo de confianza del
<span class="math inline">\(100*(1-\alpha)\)</span> por ciento en <span class="math inline">\(\theta\)</span> de cada muestra, entonces
<span class="math inline">\(100*(1-\alpha)\)</span> por ciento de estos intervalos contendrán el verdadero
valor de <span class="math inline">\(\theta\)</span>.</p>
<div id="intervalo-de-confianza-para-la-media-asumiendo-varianza-conocida." class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Intervalo de confianza para la media, asumiendo varianza conocida.<a href="estimaciones.html#intervalo-de-confianza-para-la-media-asumiendo-varianza-conocida." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sea <span class="math inline">\(X\)</span> una va con media desconocida <span class="math inline">\(\mu\)</span> y varianza conocida
<span class="math inline">\(\sigma^2\)</span>. Suponga que se toma una muestra aleatoria de tamaño <span class="math inline">\(n\)</span>,
<span class="math inline">\(X_1,X_2,\ldots,X_n\)</span>. Puede obtenerse un intervalo de confianza del
<span class="math inline">\(100*(1-\alpha)\)</span> por ciento en <span class="math inline">\(\mu\)</span> considerando la distribución de
muestreo de <span class="math inline">\(X\)</span> de la media muestral <span class="math inline">\(\bar{x}\)</span>.</p>
<p>Por el teorema del límite central sabemos que:</p>
<p><span class="math display">\[\bar{x}\sim N\left(\mu,\frac{\sigma^2}{n}\right)\]</span></p>
<p>bajo ciertas condiciones (<span class="math inline">\(n&gt;20\)</span>). Así:</p>
<p><span class="math display">\[Z=\frac{\bar{x}-\mu}{\frac{\sigma}{\sqrt{n}}} \quad \rightarrow \quad Z\sim N(0,1)\]</span></p>
<p>Teniendo a <span class="math inline">\(Z\sim N(0,1)\)</span>, para armar el intervalo de confianza basta con trabajar
sobre:</p>
<p><span class="math display">\[P(L\leq Z\leq U)=1-\alpha\]</span></p>
<p>Para un intervalo de confianza <span class="math inline">\(L \leq \theta \le U\)</span> se debe asegurar que la precisión de los lados sea la misma, <span class="math inline">\(\theta-L=U-\theta\)</span>.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="estimaciones.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x),<span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>),<span class="at">xlab=</span><span class="st">&quot;z&quot;</span>)</span>
<span id="cb169-2"><a href="estimaciones.html#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>)</span>
<span id="cb169-3"><a href="estimaciones.html#cb169-3" aria-hidden="true" tabindex="-1"></a>sx<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fu">seq</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fu">qnorm</span>(<span class="fl">0.025</span>),<span class="fl">0.01</span>),<span class="fu">qnorm</span>(<span class="fl">0.025</span>))</span>
<span id="cb169-4"><a href="estimaciones.html#cb169-4" aria-hidden="true" tabindex="-1"></a>sy<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fu">qnorm</span>(<span class="fl">0.025</span>),<span class="fl">0.01</span>)),<span class="dv">0</span>)</span>
<span id="cb169-5"><a href="estimaciones.html#cb169-5" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(sx,sy,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb169-6"><a href="estimaciones.html#cb169-6" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">*</span>sx,sy,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="estimaciones.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="co">#para encontrar los z_{alpha/2}</span></span>
<span id="cb170-2"><a href="estimaciones.html#cb170-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.1</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#10%</span></span></code></pre></div>
<pre><code>## [1] -1.644854</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="estimaciones.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#5%</span></span></code></pre></div>
<pre><code>## [1] -1.959964</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="estimaciones.html#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.01</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#1%</span></span></code></pre></div>
<pre><code>## [1] -2.575829</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="estimaciones.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="co">#para encontrar los z_{1-alpha/2}</span></span>
<span id="cb176-2"><a href="estimaciones.html#cb176-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="fl">-0.1</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#10%</span></span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="estimaciones.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#5%</span></span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="estimaciones.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="fl">-0.01</span><span class="sc">/</span><span class="dv">2</span>)<span class="co">#1%</span></span></code></pre></div>
<pre><code>## [1] 2.575829</code></pre>
<p>Si <span class="math inline">\(\alpha=0.05\)</span></p>
<p><span class="math display">\[P(L\leq Z\leq U)=0.95\]</span></p>
<p><span class="math display">\[P(-Z_{\alpha/2}\leq Z\leq Z_{\alpha/2})=1-\alpha\]</span></p>
<p><span class="math display">\[P\left(-Z_{\alpha/2}\leq \frac{\bar{X}-\mu}{\frac{\sigma}{\sqrt{n}}} \leq Z_{\alpha/2}\right)=1-\alpha\]</span></p>
<p><span class="math display">\[P\left(\bar{X}-Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\leq\mu \leq \bar{X}+Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right)=1-\alpha\]</span>
Así de esta manera tenemos identificados a <span class="math inline">\(L\)</span> y <span class="math inline">\(U\)</span> para <span class="math inline">\(\mu\)</span> con
varianza conocida.</p>
<p><span class="math display">\[L=\bar{X}-Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\]</span>
<span class="math display">\[U=\bar{X}+Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\]</span></p>
<p><span class="math inline">\(\alpha\)</span> es conocida como el nivel de significancia y <span class="math inline">\(1-\alpha\)</span> como la confiabilidad. Los valores más usuales de <span class="math inline">\(\alpha\)</span> son 0.01, 0.05 y 0.1, para estudios sobre ciencias de la salud el valor recomendado es de 0.01 o menor, para las ciencias sociales y económicas el valor recomendado es 0.05. Para la distribución normal los valores de <span class="math inline">\(Z_{\alpha/2}\)</span> son:</p>
<ul>
<li><span class="math inline">\(\alpha=0.1\)</span>, <span class="math inline">\(Z_{\alpha/2}=Z_{0.05}=1.64\)</span> (90% confiabilidad)</li>
<li><span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(Z_{\alpha/2}=Z_{0.025}=1.96\)</span> (95% confiabilidad)</li>
<li><span class="math inline">\(\alpha=0.01\)</span>, <span class="math inline">\(Z_{\alpha/2}=Z_{0.005}=2.58\)</span> (99% confiabilidad)</li>
</ul>
<blockquote>
<p>Ejercicio,</p>
</blockquote>
<p>Se sabe que la vida en horas de una bombilla eléctrica de 75 watts se distribuye aproximadamente normal, con <span class="math inline">\(\sigma=25\)</span> horas. Una muestra aleatoria de 20 bombillas tiene una vida media de <span class="math inline">\(\bar{x}=1014\)</span> horas. Encontrarlos intervalos de confianza al 90, 95 y 99 % de confiabilidad.</p>
<p>Solución, como información <span class="math inline">\(n=20\)</span>, para elaborar los intervalos:</p>
<p><span class="math display">\[\bar{X}-Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\leq\mu \leq \bar{X}+Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\]</span>
Al 90%</p>
<p><span class="math display">\[1014-1.64 \frac{25}{\sqrt{20}}\leq\mu \leq 1014+1.64 \frac{25}{\sqrt{20}}\]</span></p>
<p><span class="math display">\[1004.832 \leq \mu \leq 1023.168\]</span></p>
<p>Al 95%</p>
<p><span class="math display">\[1014-1.96 \frac{25}{\sqrt{20}}\leq\mu \leq 1014+1.96 \frac{25}{\sqrt{20}}\]</span></p>
<p><span class="math display">\[1003.043 \leq \mu \leq 1024.957\]</span></p>
<p>Al 99%</p>
<p><span class="math display">\[1014-2.58 \frac{25}{\sqrt{20}}\leq\mu \leq 1014+2.58 \frac{25}{\sqrt{20}}\]</span></p>
<p><span class="math display">\[999.5774 \leq \mu \leq 1028.423\]</span></p>
<p><span class="math display">\[|z_{\alpha/2}|=z_{1-\alpha/2}\]</span>
Algunos textos como el texto guía</p>
<p><span class="math display">\[z_{\alpha/2}=z_{1-\alpha/2}\]</span></p>
<div id="tamaño-de-muestra" class="section level4 hasAnchor" number="3.3.1.1">
<h4><span class="header-section-number">3.3.1.1</span> Tamaño de muestra<a href="estimaciones.html#tamaño-de-muestra" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Definamos al margen de error absoluto como:</p>
<p><span class="math display">\[\epsilon=Z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\]</span></p>
<p>Notar que es posible
despejar <span class="math inline">\(n\)</span> y esto permitirá tener una formula para definir un tamaño
de muestra condicionado a: el margen de error (<span class="math inline">\(\epsilon\)</span>), desviación
de los datos (<span class="math inline">\(\sigma\)</span>) y el nivel de confiabilidad (<span class="math inline">\(Z_{\alpha/2}\)</span>)</p>
<p><span class="math display">\[n=\frac{Z_{\alpha/2}^2*\sigma^2}{\epsilon^2}=\left(\frac{Z_{\alpha/2}*\sigma}{\epsilon} \right)^2\]</span>
Nota: Esta formula se puede utilizar en la medida que la muestra que se
seleccione sea aleatoria simple, se refiere a la selección de unidades
simples.</p>
<blockquote>
<p>Ejercicio:</p>
</blockquote>
<p>Se quiere estudiar la cantidad de dinero promedio gastado en pasajes (ida y vuelta) por los estudiantes de informática cuando van al monoblock un día cualquiera, para ello se decide hacer una encuesta aleatoria, si se fija un nivel de confiabilidad del 95% y se define que el margen de error no supere los 0.30 Bs. Calcular el tamaño de muestra necesario para esta encuesta.</p>
<p>Solución: Ya que no se cuenta con la información respecto <span class="math inline">\(\sigma\)</span> (la variabilidad) hay varias alternativas para definir este valor; buscar información de un estudio similar, plantear un <span class="math inline">\(\sigma\)</span> con base en la experiencia y la más recomendada es realizar una prueba piloto (estudio a escala reducida).</p>
<p>Se realizo una piloto sobre 10 estudiantes y las medidas fueron: 4, 6, 4, 4, 6, 5 , 8, 6, 2, 2. Por lo tanto:</p>
<p><span class="math display">\[n=\left(\frac{Z_{\alpha/2}*\sigma}{\epsilon} \right)^2=\left(\frac{Z_{\alpha/2}*s}{\epsilon} \right)^2=\left(\frac{1.96*1.89}{0.3} \right)^2=152.47\approx 153\]</span></p>
<p>Ejemplo, se busca conocer el tiempo promedio en horas/día que pasan los estudiantes de informática de la UMSA en la computadora, para ello se planea realizar una encuesta aleatoria, que logre un 95% de confiabilidad y tenga un margen de error de 0.8 horas. Definir el tamaño de muestra necesario.</p>
<p>Solución, como información se tiene: <span class="math inline">\(\epsilon=0.8\)</span>,
<span class="math inline">\(Z_{\alpha/2}=1.96\)</span>, para el valor de <span class="math inline">\(\sigma\)</span> para el calculo del tamaño de muestra se realizó una piloto en la materia de estadística II a 13 estudiantes y el resultado fue <span class="math inline">\(\sigma=2.72\)</span> (varianza muestral). Así:</p>
<p><span class="math display">\[n=\left(\frac{1.96*2.72}{0.8} \right)^2=44.41 \approx 45\]</span></p>
<p>Ejercicio, se quiere obtener el tamaño de muestra para un estudio que busca conocer el promedio de gasto en educación mensual de los hogares de los estudiantes de informática. Se quiere un nivel de confiabilidad del 90%, asumiendo un margen de error de 300 Bs. Se sabe de un estudio similar que <span class="math inline">\(\hat{\sigma}=650\)</span> Bs.</p>
<p>Solución,</p>
<p><span class="math display">\[n=\left(\frac{1.64*650}{300} \right)^2= 12.62\approx 13 \]</span>
Ejercicio, Se quiere hacer una encuesta sobre los ingresos de los hogares en un determinado barrio de La Paz, tomar como referencia un nivel de confiabilidad del 95% y 99%, un margen de error de 800 Bs. Suponiendo que <span class="math inline">\(\sigma=1300\)</span>.</p>
<ul>
<li>95%: <span class="math inline">\(10.14\approx 11\)</span></li>
<li>99%: <span class="math inline">\(17.58\approx 18\)</span></li>
</ul>
</div>
</div>
<div id="simulación-sobre-la-confiabilidad-de-los-intervalos-de-confianza." class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Simulación sobre la confiabilidad de los intervalos de confianza.<a href="estimaciones.html#simulación-sobre-la-confiabilidad-de-los-intervalos-de-confianza." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="estimaciones.html#cb182-1" aria-hidden="true" tabindex="-1"></a>N<span class="ot">&lt;-</span><span class="dv">200</span></span>
<span id="cb182-2"><a href="estimaciones.html#cb182-2" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">25</span></span>
<span id="cb182-3"><a href="estimaciones.html#cb182-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb182-4"><a href="estimaciones.html#cb182-4" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(N,<span class="dv">2</span>,<span class="dv">15</span>),<span class="dv">1</span>)<span class="co">#gasto en pasaje</span></span>
<span id="cb182-5"><a href="estimaciones.html#cb182-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 8.582</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="estimaciones.html#cb184-1" aria-hidden="true" tabindex="-1"></a>sigma<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">*</span>(<span class="dv">199</span><span class="sc">/</span><span class="dv">200</span>))</span>
<span id="cb184-2"><a href="estimaciones.html#cb184-2" aria-hidden="true" tabindex="-1"></a><span class="co"># muestras</span></span>
<span id="cb184-3"><a href="estimaciones.html#cb184-3" aria-hidden="true" tabindex="-1"></a><span class="fu">choose</span>(<span class="dv">200</span>,<span class="dv">25</span>)</span></code></pre></div>
<pre><code>## [1] 4.521713e+31</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="estimaciones.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">15</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span>
<span id="cb186-2"><a href="estimaciones.html#cb186-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(x),<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb186-3"><a href="estimaciones.html#cb186-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb186-4"><a href="estimaciones.html#cb186-4" aria-hidden="true" tabindex="-1"></a>  s<span class="ot">&lt;-</span><span class="fu">sample</span>(x,<span class="dv">25</span>)</span>
<span id="cb186-5"><a href="estimaciones.html#cb186-5" aria-hidden="true" tabindex="-1"></a>  xbar<span class="ot">&lt;-</span><span class="fu">mean</span>(s)</span>
<span id="cb186-6"><a href="estimaciones.html#cb186-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#IC 95%</span></span>
<span id="cb186-7"><a href="estimaciones.html#cb186-7" aria-hidden="true" tabindex="-1"></a>  ic<span class="ot">&lt;-</span>xbar<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span>sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb186-8"><a href="estimaciones.html#cb186-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segments</span>(ic[<span class="dv">1</span>],i,ic[<span class="dv">2</span>],i,<span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb186-9"><a href="estimaciones.html#cb186-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">mean</span>(x)<span class="sc">&gt;</span>ic[<span class="dv">2</span>] <span class="sc">|</span> <span class="fu">mean</span>(x)<span class="sc">&lt;</span>ic[<span class="dv">1</span>]){</span>
<span id="cb186-10"><a href="estimaciones.html#cb186-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">segments</span>(ic[<span class="dv">1</span>],i,ic[<span class="dv">2</span>],i,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb186-11"><a href="estimaciones.html#cb186-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb186-12"><a href="estimaciones.html#cb186-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
</div>
<div id="intervalo-de-confianza-sobre-la-diferencia-de-dos-medias-conocida-la-varianza" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Intervalo de confianza sobre la diferencia de dos medias, conocida la varianza<a href="estimaciones.html#intervalo-de-confianza-sobre-la-diferencia-de-dos-medias-conocida-la-varianza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tenemos dos va independientes, <span class="math inline">\(X_1\)</span> con media <span class="math inline">\(\mu_1\)</span> desconocida y varianza <span class="math inline">\(\sigma^2_1\)</span> conocida y <span class="math inline">\(X_2\)</span> con media <span class="math inline">\(\mu_2\)</span> desconocida y varianza <span class="math inline">\(\sigma^2_2\)</span> conocida. El objetivo es encontrar un intervalo para <span class="math inline">\(\mu_1-\mu_2\)</span>. Sea dos muestras aleatorias recopíladas para ambas va, de tal forma que <span class="math inline">\(n_1\)</span> representa el tamaño de muestra para <span class="math inline">\(X_1\)</span> y <span class="math inline">\(n_2\)</span> para <span class="math inline">\(X_2\)</span>. Recordar por el teorema del limite central, esta diferencia de medias puede ser estimada por sus medias muestrales y además se aproxima a una normal, tal que:</p>
<p><span class="math display">\[\bar{X}_1-\bar{X}_2 \sim N\left(\mu_{\bar{X}_1-\bar{X}_2}=\mu_1-\mu_2,\sigma^2_{\bar{X}_1-\bar{X}_2}=\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}\right)\]</span>
Ahora,</p>
<p><span class="math display">\[Z=\frac{\bar{X}_1-\bar{X}_2-(\mu_1-\mu_2)}{\sqrt{\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}}}\sim N(0,1)\]</span>
Dado que <span class="math inline">\(Z\sim N(0,1)\)</span>, ahora lo que queda es trabajar sobre:</p>
<p><span class="math display">\[P(-Z_{\alpha/2} \leq Z \leq Z_{\alpha/2})=1-\alpha\]</span>
Así, el limite inferior y superior esta dado por:</p>
<p><span class="math display">\[L=\bar{X}_1-\bar{X}_2-Z_{\alpha/2}\sqrt{\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}}\]</span>
<span class="math display">\[U=\bar{X}_1-\bar{X}_2+Z_{\alpha/2}\sqrt{\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}}\]</span></p>
<p>Notar que en general, dado un estimador <span class="math inline">\(\hat{\theta}\)</span> para el parámetro <span class="math inline">\(\theta\)</span>, su usamos el teorema del limite central su intervalo de confianza estará dado por:</p>
<p><span class="math display">\[IC(\theta): \quad \hat{\theta} \pm Z_{\alpha/2} \sqrt{V(\hat{\theta})} \]</span></p>
<p>Ejemplo: Se lleva a cabo pruebas de resistencia a la tensión sobre diferentes clases de largueros de aluminio utilizados en la fabricación de alas de aeroplanos comerciales. De la experiencia pasada con el proceso de fabricación de largueros y del procedimiento de prueba, se supone que las desviaciones estándar de las resistencias a la tensión son conocidas, Los datos obtenidos son:</p>
<ul>
<li>Clase de larguero 1: <span class="math inline">\(n_1=18\)</span>, <span class="math inline">\(\bar{x}_1=85.9\)</span>, <span class="math inline">\(\sigma_1=1\)</span></li>
<li>Clase de larguero 2: <span class="math inline">\(n_2=16\)</span>, <span class="math inline">\(\bar{x}_2=73.3\)</span>, <span class="math inline">\(\sigma_2=1.5\)</span></li>
</ul>
<p>Si <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span> son las verdaderas resistencias a la tensión de
ambas clases de largueros. Encuentre intervalos de confianza al 90%,
95%, 99% y 80% de confiabilidad para la diferencia de estas medias.</p>
<p>Solución, para el 90% de confiabilidad el intervalo esta dado por:</p>
<p><span class="math display">\[IC_{90\%}(\mu_1-\mu_2): 85.9-73.3 \pm 1.64*\sqrt{\frac{1^2}{18}+\frac{1.5^2}{16}}=12.6 \pm 0.73: [11.87\quad 13.33]\]</span>
<span class="math display">\[IC_{95\%}(\mu_1-\mu_2): 85.9-73.3 \pm 1.96*\sqrt{\frac{1^2}{18}+\frac{1.5^2}{16}}=12.6 \pm 0.87: [11.73\quad 13.47]\]</span>
<span class="math display">\[IC_{99\%}(\mu_1-\mu_2): 85.9-73.3 \pm 2.58*\sqrt{\frac{1^2}{18}+\frac{1.5^2}{16}}=[11.45 \quad 13.74]\]</span>
<span class="math display">\[IC_{80\%}(\mu_1-\mu_2): 85.9-73.3 \pm 1.28*\sqrt{\frac{1^2}{18}+\frac{1.5^2}{16}}=[12.03 \quad 13.17]\]</span></p>
</div>
<div id="intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-mayor-a-30." class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Intervalo de confianza para la media y la diferencia de medias con <em>varianza desconocida</em> pero muestra mayor a 30.<a href="estimaciones.html#intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-mayor-a-30." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para los 2 anteriores intervalos definidos se suponía que la varianza es conocida, cuando no sucede esto la mejor alternativa para reemplazar a <span class="math inline">\(\sigma^2\)</span> es usando <span class="math inline">\(S^2\)</span>, esto siempre y cuando el tamaño de muestra sea grande (<span class="math inline">\(n&gt;30\)</span>), para el caso de la diferencia de medias,
ambos tamaños de muestra deben ser mayores a 30 <span class="math inline">\((n_1,n_2&gt;30)\)</span>. Esto debido al teorema del limite central.</p>
<p>Para la media</p>
<p><span class="math display">\[IC_{100(1-\alpha)}(\mu): \bar{X}\pm Z_{\alpha/2} \sqrt{\frac{S^2}{n}}\]</span></p>
<p>Para la diferencia de medias</p>
<p><span class="math display">\[IC_{100(1-\alpha)}(\mu_1-\mu_2): \bar{X}_1-\bar{X}_2 \pm Z_{\alpha/2} \sqrt{\frac{S_1^2}{n_1}+\frac{S_2^2}{n_2}}\]</span>
Ejercicio:</p>
<p>Se cuenta con muestras de tamaño 35 de dos paralelos en una determinada materia, se esta estudiando las notas obtenidas en el primer parcial que era sobre 30 puntos, la información disponibles es la siguiente:</p>
<p><span class="math display">\[\bar{x}_1=18 \quad \sum_{m2} x_i=490 \quad S_1=7 \quad S_2=8.9\]</span>
Calcular los siguientes intervalos de confianza al 90%:
+ Para cada media de las poblaciones <span class="math inline">\(\mu_1, \mu_2\)</span>
+ Para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span>
+ Para la diferencia de medias <span class="math inline">\(\mu_2-\mu_1\)</span></p>
<p>Solución:</p>
<p><span class="math display">\[IC_{90\%}(\mu_1): 18\pm 1.64 \sqrt{\frac{7^2}{35}}=[16.06 \quad 19.94]\]</span>
<span class="math display">\[IC_{90\%}(\mu_1): 14\pm 1.64 \sqrt{\frac{8.9^2}{35}}=[11.53 \quad 16.47]\]</span>
<span class="math display">\[IC_{90\%}(\mu_1-\mu_2): [0.86 \quad 7.13]\]</span>
<span class="math display">\[IC_{90\%}(\mu_2-\mu_1): [-7.13 \quad -0.86]\]</span></p>
<blockquote>
<p>Ejemplo</p>
</blockquote>
<p>Se tiene una muestra de 32 estudiantes respecto la nota del primer parcial de la materia de estadística 2 de la carrera de informática, calcular un intervalo de confianza para la media al 95 y 97% de confiabilidad. Los datos son:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="estimaciones.html#cb187-1" aria-hidden="true" tabindex="-1"></a>bd<span class="ot">&lt;-</span>readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">&quot;C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">Alvaro</span><span class="sc">\\</span><span class="st">Box</span><span class="sc">\\</span><span class="st">2022</span><span class="sc">\\</span><span class="st">umsa</span><span class="sc">\\</span><span class="st">EST-145</span><span class="sc">\\</span><span class="st">r-exams</span><span class="sc">\\</span><span class="st">parcial1_notas_i2022.xlsx&quot;</span>)</span>
<span id="cb187-2"><a href="estimaciones.html#cb187-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span>bd<span class="sc">$</span>nota[<span class="sc">!</span><span class="fu">is.na</span>(bd<span class="sc">$</span>nota)]</span>
<span id="cb187-3"><a href="estimaciones.html#cb187-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">346</span>)</span>
<span id="cb187-4"><a href="estimaciones.html#cb187-4" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span><span class="fu">sample</span>(x,<span class="dv">32</span>)</span>
<span id="cb187-5"><a href="estimaciones.html#cb187-5" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>##  [1] 18 18 12  3 18  9  3 15 18 18 12  6 21  6 15
## [16] 15  9  6 18 24 15 12  9 18 18  9  9  9  9 18
## [31] 18 18</code></pre>
<p>Solución</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="estimaciones.html#cb189-1" aria-hidden="true" tabindex="-1"></a><span class="co">#95%</span></span>
<span id="cb189-2"><a href="estimaciones.html#cb189-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(s)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(s)<span class="sc">/</span><span class="dv">32</span>)</span></code></pre></div>
<pre><code>## [1] 11.40977 15.21523</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="estimaciones.html#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="co">#97</span></span>
<span id="cb191-2"><a href="estimaciones.html#cb191-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.03</span><span class="sc">/</span><span class="dv">2</span>,<span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 2.17009</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="estimaciones.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(s)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.03</span><span class="sc">/</span><span class="dv">2</span>,<span class="at">lower.tail =</span> F)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(s)<span class="sc">/</span><span class="dv">32</span>)</span></code></pre></div>
<pre><code>## [1] 11.20582 15.41918</code></pre>
<blockquote>
<p>Ejemplo 2</p>
</blockquote>
<p>se tiene el dato de una muestra aleatoria de 35 estudiantes sobre la variable horas/día en la computadora, se pide calcular los intervalos de confianza al 90, 95 y 99% de confiabilidad, los datos son:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="estimaciones.html#cb195-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">35</span></span>
<span id="cb195-2"><a href="estimaciones.html#cb195-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1517</span>)</span>
<span id="cb195-3"><a href="estimaciones.html#cb195-3" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rnorm</span>(n,<span class="fl">7.6</span>,<span class="fl">2.72</span>),<span class="dv">0</span>)</span>
<span id="cb195-4"><a href="estimaciones.html#cb195-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-5"><a href="estimaciones.html#cb195-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.64</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)<span class="co">#90%</span></span></code></pre></div>
<pre><code>## [1] 6.277474 7.608240</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="estimaciones.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)<span class="co">#95%</span></span></code></pre></div>
<pre><code>## [1] 6.147643 7.738071</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="estimaciones.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">2.58</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)<span class="co">#99%</span></span></code></pre></div>
<pre><code>## [1] 5.896096 7.989618</code></pre>
<p>Ejercicio, se tiene el dato de una muestra aleatoria de 40 personas, respecto su edad. Construya el intervalo de confianza al 95% de confiabilidad. Los datos son:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="estimaciones.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1534</span>)</span>
<span id="cb201-2"><a href="estimaciones.html#cb201-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">40</span>,<span class="dv">19</span>,<span class="dv">29</span>))</span>
<span id="cb201-3"><a href="estimaciones.html#cb201-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 20 26 25 24 22 27 21 28 23 26 23 24 27 22 20
## [16] 27 23 26 22 23 23 28 21 25 20 19 24 22 27 22
## [31] 21 28 28 24 23 24 21 28 27 24</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="estimaciones.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span><span class="dv">40</span>)</span></code></pre></div>
<pre><code>## [1] 23.12872 24.77128</code></pre>
</div>
<div id="intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-menor-a-30." class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Intervalo de confianza para la media y la diferencia de medias con varianza desconocida pero muestra menor a 30.<a href="estimaciones.html#intervalo-de-confianza-para-la-media-y-la-diferencia-de-medias-con-varianza-desconocida-pero-muestra-menor-a-30." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para producir un intervalo de confianza <em>valido</em> en estos casos, se debe realizar <strong>supuestos fuertes</strong> respecto la población de la cual proviene la información. La suposición mas usual es que la población de base viene de una <strong>normal</strong>, lo que nos lleva en distribuciones muestrales a trabajar con un distribución <span class="math inline">\(t-student\)</span>.</p>
<p>Para la media, sea:</p>
<p><span class="math display">\[t=\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}\]</span></p>
<p>Ahora <span class="math inline">\(t\sim t-student(n-1)\)</span>, al igual que para la normal el objetivo es
encontrar:</p>
<p><span class="math display">\[P(L\leq t \leq U)=1-\alpha\]</span></p>
<p><span class="math display">\[P(-t_{\alpha/2,n-1} \leq t \leq t_{\alpha/2,n-1})=1-\alpha\]</span></p>
<p>Lo que nos a:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(\mu): \bar{X} \pm t_{\alpha/2,n-1} \sqrt{\frac{\hat{S}^2}{n}}\]</span>
Usando la tabla del libro guía, buscar el valor:</p>
<p><span class="math display">\[t_{0.05,19}=1.729\]</span>
Nota: El valor de <span class="math inline">\(t_{\alpha/2,n-1}\)</span> en R.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="estimaciones.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="at">lower.tail =</span> F)<span class="co">#PARA LA NORMAL</span></span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="estimaciones.html#cb207-1" aria-hidden="true" tabindex="-1"></a><span class="co">#para la t-student</span></span>
<span id="cb207-2"><a href="estimaciones.html#cb207-2" aria-hidden="true" tabindex="-1"></a>alpha<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">0.1</span>,<span class="fl">0.05</span>,<span class="fl">0.01</span>)</span>
<span id="cb207-3"><a href="estimaciones.html#cb207-3" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">20</span></span>
<span id="cb207-4"><a href="estimaciones.html#cb207-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(alpha<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 1.729133 2.093024 2.860935</code></pre>
<blockquote>
<p>Ejercicio 1</p>
</blockquote>
<p>Se tienen las siguientes edades de una muestra de 10 personas de un grupo de universitarios egresados de la carrera de informática, se pide construir intervalos de confianza para la media de edad al 95% y 98% de confiabilidad. Los datos son:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="estimaciones.html#cb209-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">10</span>;<span class="fu">set.seed</span>(<span class="dv">237</span>)</span>
<span id="cb209-2"><a href="estimaciones.html#cb209-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(n,<span class="dv">22</span>,<span class="dv">30</span>),<span class="dv">0</span>)</span>
<span id="cb209-3"><a href="estimaciones.html#cb209-3" aria-hidden="true" tabindex="-1"></a><span class="co">#x&lt;-c(27, 26, 26, 25 ,26, 29, 26, 22, 28, 26)</span></span>
<span id="cb209-4"><a href="estimaciones.html#cb209-4" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 27 26 26 25 26 29 26 22 28 26</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="estimaciones.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="co">#solución, asumiendo que los datos provienen de una distribución normal</span></span>
<span id="cb211-2"><a href="estimaciones.html#cb211-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 26.1</code></pre>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="estimaciones.html#cb213-1" aria-hidden="true" tabindex="-1"></a>t95<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb213-2"><a href="estimaciones.html#cb213-2" aria-hidden="true" tabindex="-1"></a>t98<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.02</span><span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb213-3"><a href="estimaciones.html#cb213-3" aria-hidden="true" tabindex="-1"></a><span class="co">#95%</span></span>
<span id="cb213-4"><a href="estimaciones.html#cb213-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>t95<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] 24.7745 27.4255</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="estimaciones.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="co">#98%</span></span>
<span id="cb215-2"><a href="estimaciones.html#cb215-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>t98<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] 24.44679 27.75321</code></pre>
<blockquote>
<p>Ejercicio 2</p>
</blockquote>
<p>Suponga que se tiene el dato de 15 personas sobre sus ingresos mensuales, estos datos proviene de una muestra aleatoria. Calcular el estimador de la media e intervalos de confianza al 95% y 98% de confiabilidad.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="estimaciones.html#cb217-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">15</span></span>
<span id="cb217-2"><a href="estimaciones.html#cb217-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1423</span>)</span>
<span id="cb217-3"><a href="estimaciones.html#cb217-3" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(n,<span class="dv">500</span>,<span class="dv">10000</span>),<span class="dv">0</span>)</span>
<span id="cb217-4"><a href="estimaciones.html#cb217-4" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 3415 1271 7587 5620 1277 2620 8805 1811 5152
## [10] 4956 7823 9186 6785 3465 9672</code></pre>
<p>Solución, bajo el supuesto que los ingresos tienen un comportamiento normal, se utilizara el intervalo de confianza con la t-student.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="estimaciones.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="co">#estimador puntual</span></span></code></pre></div>
<pre><code>## [1] 5296.333</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="estimaciones.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalos de confianza</span></span>
<span id="cb221-2"><a href="estimaciones.html#cb221-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qt</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)<span class="co">#95%</span></span></code></pre></div>
<pre><code>## [1] 3680.188 6912.479</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="estimaciones.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qt</span>(<span class="fl">0.02</span><span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span>n)<span class="co">#98%</span></span></code></pre></div>
<pre><code>## [1] 3318.717 7273.950</code></pre>
<p>Ejemplo, suponga que tenemos las mediciones de la estatura en cm de un grupo de 20 personas que fue seleccionado de forma aleatoria de una determinada población, los datos son:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="estimaciones.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1421</span>)</span>
<span id="cb225-2"><a href="estimaciones.html#cb225-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">20</span>,<span class="dv">140</span>,<span class="dv">180</span>))</span>
<span id="cb225-3"><a href="estimaciones.html#cb225-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 171 173 180 152 148 166 177 179 173 167 175
## [12] 145 152 142 143 155 179 176 173 147</code></pre>
<p>Encontrar un intervalo de confianza al 95% de confiabilidad para la media poblacional.</p>
<p>Solución,</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="estimaciones.html#cb227-1" aria-hidden="true" tabindex="-1"></a>mx<span class="ot">&lt;-</span><span class="fu">mean</span>(x)</span>
<span id="cb227-2"><a href="estimaciones.html#cb227-2" aria-hidden="true" tabindex="-1"></a>ta<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">19</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb227-3"><a href="estimaciones.html#cb227-3" aria-hidden="true" tabindex="-1"></a>s2<span class="ot">&lt;-</span><span class="fu">var</span>(x)</span>
<span id="cb227-4"><a href="estimaciones.html#cb227-4" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">20</span></span>
<span id="cb227-5"><a href="estimaciones.html#cb227-5" aria-hidden="true" tabindex="-1"></a>mx<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>ta<span class="sc">*</span><span class="fu">sqrt</span>(s2<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] 157.1698 170.1302</code></pre>
<p>Para la diferencia de medias, pero con varianzas iguales <span class="math inline">\(\sigma_1=\sigma_2\)</span></p>
<p>Cuando <span class="math inline">\(n_1\)</span> o <span class="math inline">\(n_2\)</span> no superen ambas a 30, la mejor alternativa es usar
el intervalo de confianza en base a la distribución <span class="math inline">\(t\)</span>, para la
diferencia de medias el IC es:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(\mu_1-\mu_2)=\bar{X}_1-\bar{X}_2+t_{\alpha/2,n_1+n_2-2} S_p\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}\]</span></p>
<p>Con <span class="math inline">\(S^2_p\)</span> (Varianza ponderada)</p>
<p><span class="math display">\[S^2_p=\frac{(n_1-1)S^2_1+(n_2-1)S^2_2}{n_1+n_2-2}\]</span></p>
<p>Para la diferencia de medias, pero con varianzas no iguales</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(\mu_1-\mu_2)=\bar{X}_1-\bar{X}_2+t_{\alpha/2,v} \sqrt{\frac{S_1^2}{n_1}+\frac{S^2_2}{n_2}}\]</span></p>
<p><span class="math display">\[v=\frac{\left(\frac{S_1^2}{n_1}+\frac{S^2_2}{n_2} \right)^2}{\frac{(S_1^2/n_1)^2}{n_1+1}+\frac{(S^2_2/n_2)^2}{n_2+1}}-2\]</span>
Ejemplo, se tienen dos grupos donde se tomo de forma aleatoria a una muestra de ambos grupos, con el fin de estudiar la diferencia de medias para las notas de un examen, los resultados para ambos grupos fueron:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="estimaciones.html#cb229-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1421</span>)</span>
<span id="cb229-2"><a href="estimaciones.html#cb229-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">10</span>,<span class="dv">1</span>,<span class="dv">100</span>))</span>
<span id="cb229-3"><a href="estimaciones.html#cb229-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1457</span>)</span>
<span id="cb229-4"><a href="estimaciones.html#cb229-4" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">13</span>,<span class="dv">1</span>,<span class="dv">100</span>))</span>
<span id="cb229-5"><a href="estimaciones.html#cb229-5" aria-hidden="true" tabindex="-1"></a>x1</span></code></pre></div>
<pre><code>##  [1] 79 82 99 30 20 64 94 97 84 67</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="estimaciones.html#cb231-1" aria-hidden="true" tabindex="-1"></a>x2</span></code></pre></div>
<pre><code>##  [1] 73 62 57 23 59 16 65 39 81 23 74 22 20</code></pre>
<p>Armar un intervalo de confianza al 95% de confiabilidad suponiendo que las varianzas son iguales y otro para varianzas distintas.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="estimaciones.html#cb233-1" aria-hidden="true" tabindex="-1"></a>mx1<span class="ot">&lt;-</span><span class="fu">mean</span>(x1)</span>
<span id="cb233-2"><a href="estimaciones.html#cb233-2" aria-hidden="true" tabindex="-1"></a>mx2<span class="ot">&lt;-</span><span class="fu">mean</span>(x2)</span>
<span id="cb233-3"><a href="estimaciones.html#cb233-3" aria-hidden="true" tabindex="-1"></a>s21<span class="ot">&lt;-</span><span class="fu">var</span>(x1)</span>
<span id="cb233-4"><a href="estimaciones.html#cb233-4" aria-hidden="true" tabindex="-1"></a>s22<span class="ot">&lt;-</span><span class="fu">var</span>(x2)</span>
<span id="cb233-5"><a href="estimaciones.html#cb233-5" aria-hidden="true" tabindex="-1"></a>n1<span class="ot">&lt;-</span><span class="dv">10</span></span>
<span id="cb233-6"><a href="estimaciones.html#cb233-6" aria-hidden="true" tabindex="-1"></a>n2<span class="ot">&lt;-</span><span class="dv">13</span></span>
<span id="cb233-7"><a href="estimaciones.html#cb233-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimador puntual de diferencia de medias</span></span>
<span id="cb233-8"><a href="estimaciones.html#cb233-8" aria-hidden="true" tabindex="-1"></a>mx1<span class="sc">-</span>mx2</span></code></pre></div>
<pre><code>## [1] 24.36923</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="estimaciones.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo con varianzas iguales</span></span>
<span id="cb235-2"><a href="estimaciones.html#cb235-2" aria-hidden="true" tabindex="-1"></a>ta1<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,n1<span class="sc">+</span>n2<span class="dv">-2</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb235-3"><a href="estimaciones.html#cb235-3" aria-hidden="true" tabindex="-1"></a>s2p<span class="ot">&lt;-</span>((n1<span class="dv">-1</span>)<span class="sc">*</span>s21<span class="sc">+</span>(n2<span class="dv">-1</span>)<span class="sc">*</span>s22)<span class="sc">/</span>(n1<span class="sc">+</span>n2<span class="dv">-2</span>)</span>
<span id="cb235-4"><a href="estimaciones.html#cb235-4" aria-hidden="true" tabindex="-1"></a>mx1<span class="sc">-</span>mx2<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>ta1<span class="sc">*</span><span class="fu">sqrt</span>(s2p)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>n1<span class="sc">+</span><span class="dv">1</span><span class="sc">/</span>n2)</span></code></pre></div>
<pre><code>## [1]  2.132725 46.605736</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="estimaciones.html#cb237-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo con varianzas desiguales</span></span>
<span id="cb237-2"><a href="estimaciones.html#cb237-2" aria-hidden="true" tabindex="-1"></a>v<span class="ot">&lt;-</span>((s21<span class="sc">/</span>n1<span class="sc">+</span>s22<span class="sc">/</span>n2)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(((s21<span class="sc">/</span>n1)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n1<span class="sc">+</span><span class="dv">1</span>)<span class="sc">+</span>((s22<span class="sc">/</span>n2)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n2<span class="sc">+</span><span class="dv">1</span>))<span class="sc">-</span><span class="dv">2</span></span>
<span id="cb237-3"><a href="estimaciones.html#cb237-3" aria-hidden="true" tabindex="-1"></a>ta2<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,v,<span class="at">lower.tail =</span> F)</span>
<span id="cb237-4"><a href="estimaciones.html#cb237-4" aria-hidden="true" tabindex="-1"></a>mx1<span class="sc">-</span>mx2<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>ta2<span class="sc">*</span><span class="fu">sqrt</span>(s21<span class="sc">/</span>n1<span class="sc">+</span>s22<span class="sc">/</span>n2)</span></code></pre></div>
<pre><code>## [1]  1.660652 47.077810</code></pre>
</div>
<div id="intervalos-de-confianza-para-la-diferencia-de-medias-de-datos-pareados" class="section level3 hasAnchor" number="3.3.6">
<h3><span class="header-section-number">3.3.6</span> Intervalos de confianza para la diferencia de medias de datos pareados<a href="estimaciones.html#intervalos-de-confianza-para-la-diferencia-de-medias-de-datos-pareados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En general, supongamos que los datos constan de <span class="math inline">\(n\)</span> pares <span class="math inline">\((X_{11}, X_{21}), (X_{12}, X_{22})...(X_{1n}, X_{2n})\)</span>, usualmente esto sucede cuando se trabaja con observaciones en 2 puntos distintos de tiempo. Definamos las diferencias como
<span class="math inline">\(D_1=X_{11}-X_{21},D_2=X_{12}-X_{22},\ldots,D_n=X_{1n}-X_{2n}\)</span>,
estableciendo a <span class="math inline">\(D\)</span> como la va, su intervalo es:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(\mu_D=\mu_1-\mu_2): \bar{D} \pm t_{\alpha/2,n-1}*\sqrt{\frac{S^2_D}{n}} \]</span></p>
<p>Si n es grande, entonces el intervalo es dado por:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(\mu_D=\mu_1-\mu_2): \bar{D} \pm Z_{\alpha/2}*\sqrt{\frac{S^2_D}{n}} \]</span></p>
<p>Ejemplo, se tiene las notas de los parciales de una muestra de 12
estudiantes, será que los estudiantes mejoraron su rendimiento del parcial 1 al parcial 2. Construya un intervalo de confianza al 90%.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="estimaciones.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">240</span>)</span>
<span id="cb239-2"><a href="estimaciones.html#cb239-2" aria-hidden="true" tabindex="-1"></a>bd<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">id=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,<span class="at">p1=</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">40</span>,<span class="dv">80</span>)),<span class="at">p2=</span><span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">30</span>,<span class="dv">90</span>)))</span>
<span id="cb239-3"><a href="estimaciones.html#cb239-3" aria-hidden="true" tabindex="-1"></a><span class="co">#estimador puntual</span></span>
<span id="cb239-4"><a href="estimaciones.html#cb239-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd<span class="sc">$</span>p1)</span></code></pre></div>
<pre><code>## [1] 56.5</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="estimaciones.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd<span class="sc">$</span>p2)</span></code></pre></div>
<pre><code>## [1] 74.91667</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="estimaciones.html#cb243-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd<span class="sc">$</span>p2)<span class="sc">-</span><span class="fu">mean</span>(bd<span class="sc">$</span>p1)</span></code></pre></div>
<pre><code>## [1] 18.41667</code></pre>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="estimaciones.html#cb245-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creando la variable D=p2-p1</span></span>
<span id="cb245-2"><a href="estimaciones.html#cb245-2" aria-hidden="true" tabindex="-1"></a>bd<span class="sc">$</span>D<span class="ot">&lt;-</span>bd<span class="sc">$</span>p2<span class="sc">-</span>bd<span class="sc">$</span>p1</span>
<span id="cb245-3"><a href="estimaciones.html#cb245-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd<span class="sc">$</span>D)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qt</span>(<span class="fl">0.1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">11</span>,<span class="at">lower.tail =</span> F)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(bd<span class="sc">$</span>D)<span class="sc">/</span><span class="dv">12</span>)</span></code></pre></div>
<pre><code>## [1]  9.980298 26.853035</code></pre>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="estimaciones.html#cb247-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">11</span>,<span class="at">lower.tail =</span> F)<span class="co">#ver página 779 del libro guía</span></span></code></pre></div>
<pre><code>## [1] 1.795885</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="estimaciones.html#cb249-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############################</span></span>
<span id="cb249-2"><a href="estimaciones.html#cb249-2" aria-hidden="true" tabindex="-1"></a><span class="co">#suponer una muestra de 100 estudiantes</span></span>
<span id="cb249-3"><a href="estimaciones.html#cb249-3" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">100</span></span>
<span id="cb249-4"><a href="estimaciones.html#cb249-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1536</span>)</span>
<span id="cb249-5"><a href="estimaciones.html#cb249-5" aria-hidden="true" tabindex="-1"></a>bd2<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">id=</span><span class="dv">1</span><span class="sc">:</span>n,<span class="at">p1=</span><span class="fu">round</span>(<span class="fu">runif</span>(n,<span class="dv">40</span>,<span class="dv">80</span>)),<span class="at">p2=</span><span class="fu">round</span>(<span class="fu">runif</span>(n,<span class="dv">30</span>,<span class="dv">90</span>)))</span>
<span id="cb249-6"><a href="estimaciones.html#cb249-6" aria-hidden="true" tabindex="-1"></a><span class="co">#estimador puntual</span></span>
<span id="cb249-7"><a href="estimaciones.html#cb249-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd2<span class="sc">$</span>p1)</span></code></pre></div>
<pre><code>## [1] 60.27</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="estimaciones.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd2<span class="sc">$</span>p2)</span></code></pre></div>
<pre><code>## [1] 60.08</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="estimaciones.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd2<span class="sc">$</span>p2)<span class="sc">-</span><span class="fu">mean</span>(bd2<span class="sc">$</span>p1)</span></code></pre></div>
<pre><code>## [1] -0.19</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="estimaciones.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creando la variable D=p2-p1</span></span>
<span id="cb255-2"><a href="estimaciones.html#cb255-2" aria-hidden="true" tabindex="-1"></a>bd2<span class="sc">$</span>D<span class="ot">&lt;-</span>bd2<span class="sc">$</span>p2<span class="sc">-</span>bd2<span class="sc">$</span>p1</span>
<span id="cb255-3"><a href="estimaciones.html#cb255-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bd2<span class="sc">$</span>D)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.1</span><span class="sc">/</span><span class="dv">2</span>,<span class="at">lower.tail=</span>F)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">var</span>(bd2<span class="sc">$</span>D)<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] -3.466029  3.086029</code></pre>
</div>
<div id="intervalo-de-confianza-para-proporciones" class="section level3 hasAnchor" number="3.3.7">
<h3><span class="header-section-number">3.3.7</span> Intervalo de confianza para proporciones<a href="estimaciones.html#intervalo-de-confianza-para-proporciones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Si asumimos que el estimador del parámetro <span class="math inline">\(P\)</span> (proporción), se distribuye normal, es decir, <span class="math inline">\(\hat{P}\sim Normal\)</span>, bajo ciertas condiciones como que el tamaño de muestra es grande, se puede plantear al intervalo de confianza como:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(P)=\hat{P} \pm Z_{\alpha/2} * \sqrt{V(\hat{P})}\]</span>
Donde para encontrar la <span class="math inline">\(V(\hat{P})\)</span> basta con resolver la varianza del estimador de la media para valores binarios.</p>
<p><span class="math display">\[V(\bar{x})=\frac{\sigma^2}{n} =V(\hat{P})=\frac{\sigma^2_p}{n}=\frac{1}{n}\left(\frac{\sum_{i=1}^N x_i^2 }{N}-\mu^2 \right)=\frac{1}{n}\left(\frac{\sum_{i=1}^N x_i }{N}-P^2 \right)=\]</span></p>
<p><span class="math display">\[=\frac{1}{n}(P-P^2)=\frac{P(1-P)}{n}\]</span></p>
<p>Notar que esta varianza esta en términos del parámetro <span class="math inline">\(P\)</span>, por lo que recurrimos en el caso muestral a reemplazarlo por su estimador <span class="math inline">\(\hat{P}\)</span>. Así, el intervalo de confianza queda como:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(P)=\hat{P} \pm Z_{\alpha/2} * \sqrt{\frac{\hat{P}(1-\hat{P})}{n}}\]</span>
&gt; Ejercicio 1</p>
<p>En un municipio se van a realizar elecciones para la alcaldía, se tiene información a partir de una encuesta aleatoria a 60 personas que el partido X tiene un apoyo de 33 personas, calcular el intervalo de confianza al 95% para el porcentaje de apoyo al partido X. ¿Se puede afirmar con base en la encuesta que el partido X ganará?</p>
<blockquote>
<p>Solución,</p>
</blockquote>
<p>Como información <span class="math inline">\(n=60\)</span>. <span class="math inline">\(\hat{P}=33/60=0.55\)</span></p>
<p><span class="math display">\[IC_{95\%}(P_x)=0.55 \pm 1.96 * \sqrt{\frac{0.55*0.45}{60}}=\]</span></p>
<p><span class="math display">\[[0.42 \quad 0.68]\rightarrow [42.4 \quad 67.6]\%\]</span></p>
<blockquote>
<p>Ejercicio 2</p>
</blockquote>
<p>Se toma una muestra de 40 estudiantes de la materia de estadística I con base al listado de inscritos, se identificó en la muestra lo siguiente:</p>
<ul>
<li>10 estudiantes abandonaron la materia</li>
<li>18 estudiantes tienen notas de aprobación</li>
</ul>
<p>Se pide calcular los intervalos de confianza al 95% de confiabilidad para la proporción de abandono en la materia y la proporción de reprobados.</p>
<p>Si el curso tiene un total de 180 inscritos, ¿Cuál sera el intervalo de confianza (95%) de la cantidad de estudiantes que aprobaron?</p>
<p>Solución</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="estimaciones.html#cb257-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">40</span></span>
<span id="cb257-2"><a href="estimaciones.html#cb257-2" aria-hidden="true" tabindex="-1"></a>ab<span class="ot">&lt;-</span><span class="dv">10</span></span>
<span id="cb257-3"><a href="estimaciones.html#cb257-3" aria-hidden="true" tabindex="-1"></a>ap<span class="ot">&lt;-</span><span class="dv">18</span></span>
<span id="cb257-4"><a href="estimaciones.html#cb257-4" aria-hidden="true" tabindex="-1"></a>re<span class="ot">&lt;-</span><span class="dv">12</span></span>
<span id="cb257-5"><a href="estimaciones.html#cb257-5" aria-hidden="true" tabindex="-1"></a><span class="co"># estimador puntal</span></span>
<span id="cb257-6"><a href="estimaciones.html#cb257-6" aria-hidden="true" tabindex="-1"></a>p_ab<span class="ot">&lt;-</span><span class="dv">10</span><span class="sc">/</span><span class="dv">40</span></span>
<span id="cb257-7"><a href="estimaciones.html#cb257-7" aria-hidden="true" tabindex="-1"></a>p_ap<span class="ot">&lt;-</span><span class="dv">18</span><span class="sc">/</span><span class="dv">40</span></span>
<span id="cb257-8"><a href="estimaciones.html#cb257-8" aria-hidden="true" tabindex="-1"></a>p_re<span class="ot">&lt;-</span><span class="dv">12</span><span class="sc">/</span><span class="dv">40</span></span>
<span id="cb257-9"><a href="estimaciones.html#cb257-9" aria-hidden="true" tabindex="-1"></a>p_ab;p_ap; p_re</span></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<pre><code>## [1] 0.45</code></pre>
<pre><code>## [1] 0.3</code></pre>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="estimaciones.html#cb261-1" aria-hidden="true" tabindex="-1"></a>p_ab<span class="sc">*</span><span class="dv">100</span>;p_ap<span class="sc">*</span><span class="dv">100</span>; p_re<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<pre><code>## [1] 45</code></pre>
<pre><code>## [1] 30</code></pre>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="estimaciones.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo de confianza</span></span>
<span id="cb265-2"><a href="estimaciones.html#cb265-2" aria-hidden="true" tabindex="-1"></a>p_ab<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_ab<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_ab)<span class="sc">/</span>n) <span class="co">#abandonos</span></span></code></pre></div>
<pre><code>## [1] 0.115808 0.384192</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="estimaciones.html#cb267-1" aria-hidden="true" tabindex="-1"></a>p_ap<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_ap<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_ap)<span class="sc">/</span>n) <span class="co">#aprobados</span></span></code></pre></div>
<pre><code>## [1] 0.2958251 0.6041749</code></pre>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="estimaciones.html#cb269-1" aria-hidden="true" tabindex="-1"></a>p_re<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_re<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_re)<span class="sc">/</span>n) <span class="co">#reprobados</span></span></code></pre></div>
<pre><code>## [1] 0.1579845 0.4420155</code></pre>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="estimaciones.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="co">#%</span></span>
<span id="cb271-2"><a href="estimaciones.html#cb271-2" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(p_ab<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_ab<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_ab)<span class="sc">/</span>n)) <span class="co">#abandonos</span></span></code></pre></div>
<pre><code>## [1] 11.5808 38.4192</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="estimaciones.html#cb273-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(p_ap<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_ap<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_ap)<span class="sc">/</span>n)) <span class="co">#aprobados</span></span></code></pre></div>
<pre><code>## [1] 29.58251 60.41749</code></pre>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="estimaciones.html#cb275-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(p_re<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_re<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_re)<span class="sc">/</span>n))<span class="co">#reprobados</span></span></code></pre></div>
<pre><code>## [1] 15.79845 44.20155</code></pre>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="estimaciones.html#cb277-1" aria-hidden="true" tabindex="-1"></a><span class="co">#personas</span></span>
<span id="cb277-2"><a href="estimaciones.html#cb277-2" aria-hidden="true" tabindex="-1"></a><span class="dv">180</span><span class="sc">*</span>(p_ap<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_ap<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_ap)<span class="sc">/</span>n)) <span class="co">#aprobados</span></span></code></pre></div>
<pre><code>## [1]  53.24852 108.75148</code></pre>
<p>Ejemplo, en un curso se tomó una muestra aleatoria de 15 personas, respecto su estatura en centímetros, las mediciones son:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="estimaciones.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1431</span>)</span>
<span id="cb279-2"><a href="estimaciones.html#cb279-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">15</span>,<span class="dv">165</span>,<span class="dv">10</span>),<span class="dv">0</span>)</span>
<span id="cb279-3"><a href="estimaciones.html#cb279-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 163 167 156 156 178 172 152 160 140 160 168
## [12] 175 170 160 164</code></pre>
<p>Se pide encontrar al estimador de la proporción y su intervalo de confianza al 95% de confiabilidad para la proporción de estudiantes con estatura de 170 o más.</p>
<p>Solución,</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="estimaciones.html#cb281-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">15</span></span>
<span id="cb281-2"><a href="estimaciones.html#cb281-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span>(x<span class="sc">&gt;=</span><span class="dv">170</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb281-3"><a href="estimaciones.html#cb281-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0</code></pre>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="estimaciones.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="co">#el estimador de la proporción</span></span>
<span id="cb283-2"><a href="estimaciones.html#cb283-2" aria-hidden="true" tabindex="-1"></a>p<span class="ot">&lt;-</span><span class="fu">mean</span>(x)</span>
<span id="cb283-3"><a href="estimaciones.html#cb283-3" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>## [1] 0.2666667</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="estimaciones.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="co">#en porcentaje</span></span>
<span id="cb285-2"><a href="estimaciones.html#cb285-2" aria-hidden="true" tabindex="-1"></a>p<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 26.66667</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="estimaciones.html#cb287-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo</span></span>
<span id="cb287-2"><a href="estimaciones.html#cb287-2" aria-hidden="true" tabindex="-1"></a>p<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p)<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] 0.04287417 0.49045916</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="estimaciones.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo en %</span></span>
<span id="cb289-2"><a href="estimaciones.html#cb289-2" aria-hidden="true" tabindex="-1"></a>(p<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p)<span class="sc">/</span>n))<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1]  4.287417 49.045916</code></pre>
<blockquote>
<p>Ejemplo,</p>
</blockquote>
<p>La varianza del estimador de la proporción tiene la forma:</p>
<p><span class="math display">\[V(\hat{P})=\frac{P(1-P)}{n}\]</span></p>
<p>Si suponemos un tamaño de muestra <span class="math inline">\(n\)</span> conocido, en que valor de <span class="math inline">\(P\)</span> alcanza la varianza su máximo.</p>
<p>Solución</p>
<p><span class="math display">\[\frac{d V(\hat{P})}{dP}=\frac{d}{dP}\left(\frac{P}{n}-\frac{P^2}{n}\right)=\frac{1}{n}-\frac{2P}{n}=0 \rightarrow P=0.5\]</span>
También,</p>
<p><span class="math display">\[\frac{d^2 V(\hat{P})}{d^2P}=-\frac{2}{n}&lt;0 \quad (máximo)\]</span></p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="estimaciones.html#cb291-1" aria-hidden="true" tabindex="-1"></a>vp<span class="ot">&lt;-</span><span class="cf">function</span>(x){x<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>x)}</span>
<span id="cb291-2"><a href="estimaciones.html#cb291-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(vp,<span class="at">xlab=</span><span class="st">&quot;p&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;v(p)&quot;</span>,<span class="at">main=</span><span class="st">&quot;n=1&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<div id="tamaño-de-muestra-para-estimar-proporciones" class="section level4 hasAnchor" number="3.3.7.1">
<h4><span class="header-section-number">3.3.7.1</span> Tamaño de muestra para estimar proporciones<a href="estimaciones.html#tamaño-de-muestra-para-estimar-proporciones" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Para la proporción definimos el margen de error (<span class="math inline">\(\epsilon\)</span>) como:</p>
<p><span class="math display">\[\epsilon= Z_{\alpha/2} * \sqrt{\frac{\hat{P}(1-\hat{P})}{n}}\]</span></p>
<p>Ahora, podemos usar esta definición como una salida para el calculo del tamaño de muestra necesario para cometer un determinado margen de error (<span class="math inline">\(epsilon\)</span>), sujeto a un nivel de confiabilidad de <span class="math inline">\(Z_{\alpha/2}\)</span>, basta con despejar <span class="math inline">\(n\)</span> de la anterior formula.</p>
<p><span class="math display">\[n=\left(\frac{Z_{\alpha/2}}{\epsilon}\right)^2 \hat{P}(1-\hat{P})\]</span></p>
<p>Dado que definir el tamaño de muestra es un paso previo a la recolección de información, notar que se tiene total control sobre el margen de error (<span class="math inline">\(\epsilon\)</span>) y el nivel de confiabilidad (<span class="math inline">\(Z_{\alpha/2}\)</span>), sin embargo, en la formula aparece el estimador <span class="math inline">\(\hat{P}\)</span> que es el de interés, la solución para saltarnos este dilema, es elegir un <span class="math inline">\(\hat{P}\)</span> basado en un estudio similar o una prueba piloto, la otra alternativa extrema es suponer un <span class="math inline">\(\hat{P}\)</span> que haga máximo a <span class="math inline">\(n\)</span> con lo demás fijo.</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="estimaciones.html#cb292-1" aria-hidden="true" tabindex="-1"></a>tm_p<span class="ot">&lt;-</span><span class="cf">function</span>(z,e,p){</span>
<span id="cb292-2"><a href="estimaciones.html#cb292-2" aria-hidden="true" tabindex="-1"></a>  n<span class="ot">&lt;-</span>((z<span class="sc">/</span>e)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb292-3"><a href="estimaciones.html#cb292-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(n)</span>
<span id="cb292-4"><a href="estimaciones.html#cb292-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb292-5"><a href="estimaciones.html#cb292-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.05</span>,<span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## [1] 384.16</code></pre>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="estimaciones.html#cb294-1" aria-hidden="true" tabindex="-1"></a>p<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.01</span>)</span>
<span id="cb294-2"><a href="estimaciones.html#cb294-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p,<span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.05</span>,p))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<blockquote>
<p>Ejercicio,</p>
</blockquote>
<p>Una carrera en la universidad esta a punto de elegir a sus autoridades, se busca hacer una encuesta de intención de votos en los estudiantes para el candidato <span class="math inline">\(Z\)</span>, se quiere un nivel de confianza del 95%, y no errar en +- 5%. Calcular el tamaño de muestra, (1) suponiendo <span class="math inline">\(n\)</span> máxima y (2) mediante un sondeo se verifico que el candidato <span class="math inline">\(Z\)</span> tiene un 70% de apoyo.</p>
<p>Solución,</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="estimaciones.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.05</span>,<span class="fl">0.5</span>))<span class="co">#1</span></span></code></pre></div>
<pre><code>## [1] 385</code></pre>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="estimaciones.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.05</span>,<span class="fl">0.7</span>))<span class="co">#2</span></span></code></pre></div>
<pre><code>## [1] 323</code></pre>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="estimaciones.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.1</span>,<span class="fl">0.5</span>))<span class="co">#epsilon 10%</span></span></code></pre></div>
<pre><code>## [1] 97</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="estimaciones.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="fu">tm_p</span>(<span class="fl">1.96</span>,<span class="fl">0.01</span>,<span class="fl">0.5</span>))<span class="co">#epsilon 1%</span></span></code></pre></div>
<pre><code>## [1] 9604</code></pre>
<p>Nota: La muestra de 385 es valida para cualquier área, siempre y cuando la selección de la muestra se realiza de forma completamente aleatoria (<strong>azar</strong>) y provenir de una <strong>listado</strong> de la población objetivo.</p>
</div>
</div>
<div id="intervalo-de-confianza-para-diferencia-de-proporciones" class="section level3 hasAnchor" number="3.3.8">
<h3><span class="header-section-number">3.3.8</span> Intervalo de confianza para diferencia de proporciones<a href="estimaciones.html#intervalo-de-confianza-para-diferencia-de-proporciones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Esta diferencia de proporciones son ampliamente usadas cuando se comparan dos poblaciones, respecto una característica de interés sobre dos poblaciones independientes. Así el intervalo de la diferencia de proporciones esta dado por:</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(P_1-P_2)=(\hat{P}_1-\hat{P}_2) \pm Z_{\alpha/2} * \sqrt{\frac{\hat{P_1}(1-\hat{P}_1)}{n_1}+\frac{\hat{P}_2(1-\hat{P}_2)}{n_2}}\]</span></p>
<p>Donde <span class="math inline">\(\hat{P}_1\)</span> y <span class="math inline">\(\hat{P}_2\)</span> son estimaciones de proporción para la población 1 y 2, respecto una misma característica, <span class="math inline">\(n_1\)</span> y <span class="math inline">\(n_2\)</span> son los tamaños de muestra es estas poblaciones.</p>
<blockquote>
<p>Ejercicio: Se tienen muestras aleatorias de tamaño 45 de personas que se postularon a una carrera durante los semestres I-2022 y II-2022, se sabe que en el primer semestre de la muestra aprobaron 22 postulantes, mientras que en el segundo semestre fueron 27, obtener el intervalo de confianza al 95% para la diferencia de proporciones del semestre II respecto el I. (5 minutos)</p>
</blockquote>
<p>Solución:</p>
<p><span class="math display">\[IC_{95\%}(P_{II}-P_{I})=\frac{27}{45}-\frac{22}{45} \pm 1.96 * \sqrt{\frac{27/45(1-27/45)}{45}+\frac{22/45(1-22/45)}{45}}\]</span>
<span class="math display">\[=\frac{5}{45}\pm 0.2045\rightarrow [-0.093 \quad 0.315]  \]</span></p>
<blockquote>
<p>Ejemplo,</p>
</blockquote>
<p>En una muestra aleatoria de 20 estudiantes se midió la estatura del grupo, se tiene conocimiento del sexo de los estudiantes y se busca estimar la diferencia de proporciones por hombre y mujer de la proporción de estudiantes que superan los 170 cm de estatura. Los datos son:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="estimaciones.html#cb303-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">20</span></span>
<span id="cb303-2"><a href="estimaciones.html#cb303-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1501</span>)</span>
<span id="cb303-3"><a href="estimaciones.html#cb303-3" aria-hidden="true" tabindex="-1"></a>estatura<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rnorm</span>(n,<span class="dv">165</span>,<span class="dv">10</span>),<span class="dv">0</span>)</span>
<span id="cb303-4"><a href="estimaciones.html#cb303-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1501</span>)</span>
<span id="cb303-5"><a href="estimaciones.html#cb303-5" aria-hidden="true" tabindex="-1"></a>mujer<span class="ot">&lt;-</span><span class="fu">rbinom</span>(n,<span class="dv">1</span>,<span class="fl">0.4</span>)</span>
<span id="cb303-6"><a href="estimaciones.html#cb303-6" aria-hidden="true" tabindex="-1"></a>bd<span class="ot">&lt;-</span><span class="fu">data.frame</span>(estatura,mujer)</span>
<span id="cb303-7"><a href="estimaciones.html#cb303-7" aria-hidden="true" tabindex="-1"></a>bd</span></code></pre></div>
<pre><code>##    estatura mujer
## 1       161     0
## 2       179     0
## 3       171     1
## 4       152     0
## 5       141     1
## 6       168     0
## 7       168     0
## 8       173     1
## 9       155     0
## 10      169     0
## 11      160     1
## 12      177     1
## 13      164     1
## 14      165     1
## 15      159     1
## 16      172     1
## 17      158     0
## 18      169     0
## 19      172     1
## 20      166     0</code></pre>
<p>Se pide calcular el estimador puntual de la diferencia de proporciones y el intervalo de confianza al 90% de confiabilidad.</p>
<p>Solución, algunos parámetros del ejercicio <span class="math inline">\(n_1=10\)</span> , <span class="math inline">\(n_2=10\)</span>, las proporciones:</p>
<p><span class="math display">\[\hat{P}_{1,h}=\frac{\#a}{n_1}=\frac{1}{10}=0.1\]</span>
<span class="math display">\[\hat{P}_{2,m}=\frac{\#a}{n_2}=\frac{5}{10}=0.5\]</span></p>
<p>El estimador puntual es dado por:</p>
<p><span class="math display">\[\hat{P}_1-\hat{P}_2=0.1-0.5=-0.4\]</span></p>
<p>Ahora, el intervalo de confianza</p>
<p><span class="math display">\[IC_{100*(1-\alpha)}(P_1-P_2)=-0.4 \pm 1.64 * \sqrt{\frac{0.1*0.9}{10}+\frac{0.5*0.5}{10}}=-0.4 \pm 0.3024\]</span>
<span class="math display">\[IC_{100*(1-\alpha)}(P_1-P_2)=[-0.702 \quad -0.098]\]</span></p>
</div>
<div id="intervalo-de-confianza-para-la-varianza" class="section level3 hasAnchor" number="3.3.9">
<h3><span class="header-section-number">3.3.9</span> Intervalo de confianza para la varianza<a href="estimaciones.html#intervalo-de-confianza-para-la-varianza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que <span class="math inline">\(X\sim Normal(\mu,\sigma)\)</span> ambos parámetros desconocidos. Sea <span class="math inline">\(X_1,X_2,\ldots,X_n\)</span> una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span>. Recodar que la varianza muestra sigue una distribución de muestreo tipo <span class="math inline">\(\chi^2\)</span>.</p>
<p><span class="math display">\[\chi^2=\frac{(n-1)S^2}{\sigma^2}\]</span>
Para desarrollar el intervalo usamos esta distribución:</p>
<p><span class="math display">\[P(\chi^2_{1-\alpha/2,n-1} \leq \chi^2 \leq \chi^2_{\alpha/2,n-1})=1-\alpha\]</span>
<span class="math display">\[IC_{100*(1-\alpha)}(\sigma^2): \left[\frac{(n-1){S}^2}{\chi^2_{\alpha/2,n-1}} \quad  \frac{(n-1){S}^2}{\chi^2_{1-\alpha/2,n-1}}\right]\]</span></p>
<blockquote>
<p>Ejercicio, se tiene una muestra aleatoria de 10 personas respecto la cantidad de horas de sueño del día anterior. Los resultados son:</p>
</blockquote>
<p>11 8 4 7 11 9 5 10 9 11</p>
<p>Calcular el intervalo de confianza al 95% para la varianza de la variable horas de sueño.</p>
<p>Solución, como información, <span class="math inline">\(n=10\)</span>. <span class="math inline">\(S^2=6.28\)</span></p>
<p><span class="math display">\[IC_{95\%}(\sigma^2): \left[\frac{9*6.28}{\chi^2_{0.05/2,9}} \quad  \frac{9*6.28}{\chi^2_{1-0.05/2,9}}\right]=\left[\frac{56.52}{19.02} \quad  \frac{56.52}{2.7}\right]\]</span>
<span class="math display">\[=[2.97 \quad 20.93]\]</span></p>
</div>
<div id="intervalo-de-confianza-para-el-cociente-de-varianzas" class="section level3 hasAnchor" number="3.3.10">
<h3><span class="header-section-number">3.3.10</span> Intervalo de confianza para el cociente de varianzas<a href="estimaciones.html#intervalo-de-confianza-para-el-cociente-de-varianzas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El objetivo de esta medida es tener un intervalo para el cociente de las varianzas de dos poblaciones, esto puede servir para identificar que población (con que variable) tiene mayor variabilidad. El parámetro es:</p>
<p><span class="math display">\[\theta=\frac{\sigma^2_1}{\sigma^2_2}\]</span>
Supongamos que <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span> son va normales con media <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span> desconocidas y varianzas <span class="math inline">\(\sigma^2_1\)</span>, <span class="math inline">\(\sigma^2_2\)</span> también desconocidas. Sean dos muestras aleatorias de <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span> de tamaño <span class="math inline">\(n_1\)</span> y <span class="math inline">\(n_2\)</span> y sean <span class="math inline">\(S^2_1\)</span> y <span class="math inline">\(S^2_2\)</span> las varianzas de las muestras. Para armar el intervalo de confianza recurrimos a la distribución <span class="math inline">\(F\)</span>.</p>
<p><span class="math display">\[F=\frac{\frac{S^2_2}{\sigma^2_2}}{\frac{S^2_1}{\sigma^2_1}}\]</span></p>
<p>Nota: Recordar que la distribución <span class="math inline">\(F\)</span> es el cociente de chi-cuadrados sobre sus grados de libertad.</p>
<p>Se busca:</p>
<p><span class="math display">\[P(F_{1-\alpha/2,n_2-1,n_1-1} \leq F \leq F_{\alpha/2,n_2-1,n_1-1})=1-\alpha\]</span></p>
<p><span class="math display">\[IC_{100*(1-\alpha)}\left(\frac{\sigma^2_1}{\sigma^2_2}\right): \left[\frac{{S}^2_1}{{S}^2_2} F_{1-\alpha/2,n_2-1,n_1-1} \quad \frac{{S}^2_1}{{S}^2_2} F_{\alpha/2,n_2-1,n_1-1}\right]\]</span>
Para encontrar el valor de F en R. Suponer una muestra para ambas poblaciones de 13 y un nivel de confiabilidad del 95%</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="estimaciones.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">12</span>,<span class="dv">12</span>,<span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.3051314</code></pre>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="estimaciones.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">12</span>,<span class="dv">12</span>,<span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 3.277277</code></pre>
</div>
</div>
<div id="ejercicios" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Ejercicios<a href="estimaciones.html#ejercicios" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Un ingeniero de control de calidad midió el espesor de la pared de 25 botellas de vidrio de dos litros. La media de la muestra fue 4.05 mm y la desviación estándar de la muestra <span class="math inline">\(\hat{S}=.08\)</span> mm. Determine un intervalo de confianza:</li>
</ol>
<ul>
<li>al 90 % de confiabilidad (dos lados)</li>
<li>inferior del 90 por ciento</li>
</ul>
<p>respecto al espesor de pared medio.</p>
<p>Solución,</p>
<p><span class="math display">\[IC(\bar{x})_{90\%}=\bar{x} \pm t_{\alpha/2,n-1} \sqrt{\frac{\hat{S}^2}{n}}=4.05\pm 1.71 \sqrt{\frac{0.08^2}{25}}\]</span></p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="estimaciones.html#cb309-1" aria-hidden="true" tabindex="-1"></a>ta<span class="ot">&lt;-</span><span class="fu">qt</span>(<span class="fl">0.1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">24</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb309-2"><a href="estimaciones.html#cb309-2" aria-hidden="true" tabindex="-1"></a><span class="fl">4.05</span><span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>ta<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fl">0.08</span><span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">25</span>)</span></code></pre></div>
<pre><code>## [1] 4.022626 4.077374</code></pre>
<p><span class="math display">\[IC(\bar{x})_{90\%}=[4.02 \quad 4.08]\]</span>
Para el intervalo de confianza inferior. Recordar que para el intervalo de confianza de 2 lados, la formula es:</p>
<p><span class="math display">\[P(L&lt;\theta&lt;U)=1-\alpha\]</span>
Mientras para un intervalo inferior, la formula es:</p>
<p><span class="math display">\[P(L&lt;\theta)=1-\alpha\]</span></p>
<p><span class="math display">\[IC(\bar{x})_{90\%, inferior}=\bar{x} - t_{\alpha,n-1} \sqrt{\frac{\hat{S}^2}{n}}=4.05- 1.32 \sqrt{\frac{0.08^2}{25}}\]</span></p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="estimaciones.html#cb311-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.1</span>,<span class="dv">24</span>,<span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 1.317836</code></pre>
<p><span class="math display">\[L: 4.03mm\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Un ingeniero industrial está interesado en estimar el tiempo medio requerido para ensamblar una tarjeta de circuito impreso. ¿Qué tan grande debe ser la muestra si el ingeniero desea tener una confianza del 95 por ciento de que el error en la estimación de la media es menor que .25 minutos? La desviación estándar del tiempo de ensamble es .45 minutos.</li>
</ol>
<p>Solución, sean los datos <span class="math inline">\(Z_{\alpha/2}=1.96\)</span>, <span class="math inline">\(\sigma=0.45\)</span>, <span class="math inline">\(\epsilon=0.25\)</span></p>
<p><span class="math display">\[n=\left(\frac{Z_{\alpha/2}*\sigma}{\epsilon} \right)^2=\left(\frac{1.96*0.45}{0.25}\right)^2=12.45\approx13\]</span>
3. Dada la siguiente muestra aleatoria por hombre y mujer, respecto sus ingresos:</p>
<ul>
<li>Hombre: 2078, 3565, 3767, 3600, 2907, 1299, 3483, 8475, 2425, 3500, 3118, 3377, 3897, 21883, 9717, 2078, 8167</li>
<li>Mujeres: 1905, 9500, 996, 3250, 3335, 433, 2917, 616, 1625, 1104, 2050, 3000, 1625</li>
</ul>
<p>se pide calcular intervalos de confianza para la varianza para ambas poblaciones, y para el cociente de varianzas entre <span class="math inline">\(Hombre/Mujer\)</span> y <span class="math inline">\(Mujer/Hombre\)</span>. Estos intervalos al 95 % de confiabilidad. (Asumir normalidad de los datos de origen).</p>
<p>Solución:</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="estimaciones.html#cb313-1" aria-hidden="true" tabindex="-1"></a>hh<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">2078</span>,  <span class="dv">3565</span>,  <span class="dv">3767</span>,  <span class="dv">3600</span>,  <span class="dv">2907</span>,  <span class="dv">1299</span>,  <span class="dv">3483</span>,  <span class="dv">8475</span>,  <span class="dv">2425</span>,  <span class="dv">3500</span>,  <span class="dv">3118</span>,  <span class="dv">3377</span>,  <span class="dv">3897</span>, <span class="dv">21883</span>,  <span class="dv">9717</span>,  <span class="dv">2078</span>,  <span class="dv">8167</span>)</span>
<span id="cb313-2"><a href="estimaciones.html#cb313-2" aria-hidden="true" tabindex="-1"></a>mm<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1905</span>, <span class="dv">9500</span>, <span class="dv">996</span>, <span class="dv">3250</span>, <span class="dv">3335</span>, <span class="dv">433</span>, <span class="dv">2917</span>, <span class="dv">616</span>, <span class="dv">1625</span>, <span class="dv">1104</span>, <span class="dv">2050</span>, <span class="dv">3000</span>, <span class="dv">1625</span>)</span>
<span id="cb313-3"><a href="estimaciones.html#cb313-3" aria-hidden="true" tabindex="-1"></a>nh<span class="ot">&lt;-</span><span class="dv">17</span>;nm<span class="ot">&lt;-</span><span class="dv">13</span></span>
<span id="cb313-4"><a href="estimaciones.html#cb313-4" aria-hidden="true" tabindex="-1"></a><span class="co">#estimador de varianzas</span></span>
<span id="cb313-5"><a href="estimaciones.html#cb313-5" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(hh)<span class="co">#puntual hombres S^2</span></span></code></pre></div>
<pre><code>## [1] 24271163</code></pre>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="estimaciones.html#cb315-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(mm)<span class="co">#puntual mujeres S^2</span></span></code></pre></div>
<pre><code>## [1] 5400214</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="estimaciones.html#cb317-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo hombres</span></span>
<span id="cb317-2"><a href="estimaciones.html#cb317-2" aria-hidden="true" tabindex="-1"></a>lih<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">*</span>(nh<span class="dv">-1</span>))<span class="sc">/</span><span class="fu">qchisq</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb317-3"><a href="estimaciones.html#cb317-3" aria-hidden="true" tabindex="-1"></a>lsh<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">*</span>(nh<span class="dv">-1</span>))<span class="sc">/</span><span class="fu">qchisq</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb317-4"><a href="estimaciones.html#cb317-4" aria-hidden="true" tabindex="-1"></a>lih;<span class="fu">var</span>(hh);lsh</span></code></pre></div>
<pre><code>## [1] 13462780</code></pre>
<pre><code>## [1] 24271163</code></pre>
<pre><code>## [1] 56218511</code></pre>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="estimaciones.html#cb321-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo mujeres</span></span>
<span id="cb321-2"><a href="estimaciones.html#cb321-2" aria-hidden="true" tabindex="-1"></a>limj<span class="ot">&lt;-</span>(<span class="fu">var</span>(mm)<span class="sc">*</span>(nm<span class="dv">-1</span>))<span class="sc">/</span><span class="fu">qchisq</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb321-3"><a href="estimaciones.html#cb321-3" aria-hidden="true" tabindex="-1"></a>lsmj<span class="ot">&lt;-</span>(<span class="fu">var</span>(mm)<span class="sc">*</span>(nm<span class="dv">-1</span>))<span class="sc">/</span><span class="fu">qchisq</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb321-4"><a href="estimaciones.html#cb321-4" aria-hidden="true" tabindex="-1"></a>limj;<span class="fu">var</span>(mm);lsmj</span></code></pre></div>
<pre><code>## [1] 2776857</code></pre>
<pre><code>## [1] 5400214</code></pre>
<pre><code>## [1] 14715187</code></pre>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="estimaciones.html#cb325-1" aria-hidden="true" tabindex="-1"></a><span class="do">###########################</span></span>
<span id="cb325-2"><a href="estimaciones.html#cb325-2" aria-hidden="true" tabindex="-1"></a><span class="co">#cociente de varianza H/M</span></span>
<span id="cb325-3"><a href="estimaciones.html#cb325-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb325-4"><a href="estimaciones.html#cb325-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm)<span class="co">#puntual</span></span></code></pre></div>
<pre><code>## [1] 4.494481</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="estimaciones.html#cb327-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalos</span></span>
<span id="cb327-2"><a href="estimaciones.html#cb327-2" aria-hidden="true" tabindex="-1"></a>lihm<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm))<span class="sc">*</span><span class="fu">qf</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb327-3"><a href="estimaciones.html#cb327-3" aria-hidden="true" tabindex="-1"></a>lshm<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm))<span class="sc">*</span><span class="fu">qf</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb327-4"><a href="estimaciones.html#cb327-4" aria-hidden="true" tabindex="-1"></a>lihm; <span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm); lshm</span></code></pre></div>
<pre><code>## [1] 1.426128</code></pre>
<pre><code>## [1] 4.494481</code></pre>
<pre><code>## [1] 12.98477</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="estimaciones.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="co">#99 confiabilidad</span></span>
<span id="cb331-2"><a href="estimaciones.html#cb331-2" aria-hidden="true" tabindex="-1"></a>lihm<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm))<span class="sc">*</span><span class="fu">qf</span>(<span class="dv">1</span><span class="fl">-0.01</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb331-3"><a href="estimaciones.html#cb331-3" aria-hidden="true" tabindex="-1"></a>lshm<span class="ot">&lt;-</span>(<span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm))<span class="sc">*</span><span class="fu">qf</span>(<span class="fl">0.01</span><span class="sc">/</span><span class="dv">2</span>,nm<span class="dv">-1</span>,nh<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb331-4"><a href="estimaciones.html#cb331-4" aria-hidden="true" tabindex="-1"></a>lihm; <span class="fu">var</span>(hh)<span class="sc">/</span><span class="fu">var</span>(mm); lshm</span></code></pre></div>
<pre><code>## [1] 0.9615647</code></pre>
<pre><code>## [1] 4.494481</code></pre>
<pre><code>## [1] 18.42446</code></pre>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="estimaciones.html#cb335-1" aria-hidden="true" tabindex="-1"></a><span class="do">###########################</span></span>
<span id="cb335-2"><a href="estimaciones.html#cb335-2" aria-hidden="true" tabindex="-1"></a><span class="co">#cociente de varianza M/H</span></span>
<span id="cb335-3"><a href="estimaciones.html#cb335-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb335-4"><a href="estimaciones.html#cb335-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(mm)<span class="sc">/</span><span class="fu">var</span>(hh)<span class="co">#puntual</span></span></code></pre></div>
<pre><code>## [1] 0.2224951</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="estimaciones.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalos</span></span>
<span id="cb337-2"><a href="estimaciones.html#cb337-2" aria-hidden="true" tabindex="-1"></a>limh<span class="ot">&lt;-</span>(<span class="fu">var</span>(mm)<span class="sc">/</span><span class="fu">var</span>(hh))<span class="sc">*</span><span class="fu">qf</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,nh<span class="dv">-1</span>,nm<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb337-3"><a href="estimaciones.html#cb337-3" aria-hidden="true" tabindex="-1"></a>lsmh<span class="ot">&lt;-</span>(<span class="fu">var</span>(mm)<span class="sc">/</span><span class="fu">var</span>(hh))<span class="sc">*</span><span class="fu">qf</span>(<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>,nh<span class="dv">-1</span>,nm<span class="dv">-1</span>,<span class="at">lower.tail =</span> F)</span>
<span id="cb337-4"><a href="estimaciones.html#cb337-4" aria-hidden="true" tabindex="-1"></a>limh; <span class="fu">var</span>(mm)<span class="sc">/</span><span class="fu">var</span>(hh); lsmh</span></code></pre></div>
<pre><code>## [1] 0.0770133</code></pre>
<pre><code>## [1] 0.2224951</code></pre>
<pre><code>## [1] 0.7011992</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tema-2-distribuciones-muestrales.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="prueba-de-hipótesis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
